type Query {
	Page(id: Int!, draft: Boolean, trash: Boolean): Page
	Pages(
		draft: Boolean
		where: Page_where
		limit: Int
		page: Int
		pagination: Boolean
		sort: String
		trash: Boolean
	): Pages
	countPages(draft: Boolean, trash: Boolean, where: Page_where): countPages
	docAccessPage(id: Int!): pagesDocAccess
	User(id: Int!, draft: Boolean, trash: Boolean): User
	Users(
		draft: Boolean
		where: User_where
		limit: Int
		page: Int
		pagination: Boolean
		sort: String
		trash: Boolean
	): Users
	countUsers(draft: Boolean, trash: Boolean, where: User_where): countUsers
	docAccessUser(id: Int!): usersDocAccess
	meUser: usersMe
	initializedUser: Boolean
	Tenant(id: Int!, draft: Boolean, trash: Boolean): Tenant
	Tenants(
		draft: Boolean
		where: Tenant_where
		limit: Int
		page: Int
		pagination: Boolean
		sort: String
		trash: Boolean
	): Tenants
	countTenants(
		draft: Boolean
		trash: Boolean
		where: Tenant_where
	): countTenants
	docAccessTenant(id: Int!): tenantsDocAccess
	PayloadLockedDocument(
		id: Int!
		draft: Boolean
		trash: Boolean
	): PayloadLockedDocument
	PayloadLockedDocuments(
		draft: Boolean
		where: PayloadLockedDocument_where
		limit: Int
		page: Int
		pagination: Boolean
		sort: String
		trash: Boolean
	): PayloadLockedDocuments
	countPayloadLockedDocuments(
		draft: Boolean
		trash: Boolean
		where: PayloadLockedDocument_where
	): countPayloadLockedDocuments
	docAccessPayloadLockedDocument(id: Int!): payload_locked_documentsDocAccess
	PayloadPreference(id: Int!, draft: Boolean, trash: Boolean): PayloadPreference
	PayloadPreferences(
		draft: Boolean
		where: PayloadPreference_where
		limit: Int
		page: Int
		pagination: Boolean
		sort: String
		trash: Boolean
	): PayloadPreferences
	countPayloadPreferences(
		draft: Boolean
		trash: Boolean
		where: PayloadPreference_where
	): countPayloadPreferences
	docAccessPayloadPreference(id: Int!): payload_preferencesDocAccess
	Access: Access
}

type Page {
	id: Int!
	tenant: Tenant
	title: String
	slug: String
	updatedAt: DateTime
	createdAt: DateTime
}

type Tenant {
	id: Int!
	name: String!
	domain: String
	slug: String!
	allowPublicRead: Boolean
	updatedAt: DateTime
	createdAt: DateTime
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

type Pages {
	docs: [Page!]!
	hasNextPage: Boolean!
	hasPrevPage: Boolean!
	limit: Int!
	nextPage: Int
	offset: Int
	page: Int!
	pagingCounter: Int!
	prevPage: Int
	totalDocs: Int!
	totalPages: Int!
}

input Page_where {
	tenant: Page_tenant_operator
	title: Page_title_operator
	slug: Page_slug_operator
	updatedAt: Page_updatedAt_operator
	createdAt: Page_createdAt_operator
	id: Page_id_operator
	AND: [Page_where_and]
	OR: [Page_where_or]
}

input Page_tenant_operator {
	equals: JSON
	not_equals: JSON
	in: [JSON]
	not_in: [JSON]
	all: [JSON]
	exists: Boolean
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON
	@specifiedBy(
		url: "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf"
	)

input Page_title_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input Page_slug_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input Page_updatedAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input Page_createdAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input Page_id_operator {
	equals: Int
	not_equals: Int
	greater_than_equal: Int
	greater_than: Int
	less_than_equal: Int
	less_than: Int
	exists: Boolean
}

input Page_where_and {
	tenant: Page_tenant_operator
	title: Page_title_operator
	slug: Page_slug_operator
	updatedAt: Page_updatedAt_operator
	createdAt: Page_createdAt_operator
	id: Page_id_operator
	AND: [Page_where_and]
	OR: [Page_where_or]
}

input Page_where_or {
	tenant: Page_tenant_operator
	title: Page_title_operator
	slug: Page_slug_operator
	updatedAt: Page_updatedAt_operator
	createdAt: Page_createdAt_operator
	id: Page_id_operator
	AND: [Page_where_and]
	OR: [Page_where_or]
}

type countPages {
	totalDocs: Int
}

type pagesDocAccess {
	fields: PagesDocAccessFields
	create: PagesCreateDocAccess
	read: PagesReadDocAccess
	update: PagesUpdateDocAccess
	delete: PagesDeleteDocAccess
}

type PagesDocAccessFields {
	tenant: PagesDocAccessFields_tenant
	title: PagesDocAccessFields_title
	slug: PagesDocAccessFields_slug
	updatedAt: PagesDocAccessFields_updatedAt
	createdAt: PagesDocAccessFields_createdAt
}

type PagesDocAccessFields_tenant {
	create: PagesDocAccessFields_tenant_Create
	read: PagesDocAccessFields_tenant_Read
	update: PagesDocAccessFields_tenant_Update
	delete: PagesDocAccessFields_tenant_Delete
}

type PagesDocAccessFields_tenant_Create {
	permission: Boolean!
}

type PagesDocAccessFields_tenant_Read {
	permission: Boolean!
}

type PagesDocAccessFields_tenant_Update {
	permission: Boolean!
}

type PagesDocAccessFields_tenant_Delete {
	permission: Boolean!
}

type PagesDocAccessFields_title {
	create: PagesDocAccessFields_title_Create
	read: PagesDocAccessFields_title_Read
	update: PagesDocAccessFields_title_Update
	delete: PagesDocAccessFields_title_Delete
}

type PagesDocAccessFields_title_Create {
	permission: Boolean!
}

type PagesDocAccessFields_title_Read {
	permission: Boolean!
}

type PagesDocAccessFields_title_Update {
	permission: Boolean!
}

type PagesDocAccessFields_title_Delete {
	permission: Boolean!
}

type PagesDocAccessFields_slug {
	create: PagesDocAccessFields_slug_Create
	read: PagesDocAccessFields_slug_Read
	update: PagesDocAccessFields_slug_Update
	delete: PagesDocAccessFields_slug_Delete
}

type PagesDocAccessFields_slug_Create {
	permission: Boolean!
}

type PagesDocAccessFields_slug_Read {
	permission: Boolean!
}

type PagesDocAccessFields_slug_Update {
	permission: Boolean!
}

type PagesDocAccessFields_slug_Delete {
	permission: Boolean!
}

type PagesDocAccessFields_updatedAt {
	create: PagesDocAccessFields_updatedAt_Create
	read: PagesDocAccessFields_updatedAt_Read
	update: PagesDocAccessFields_updatedAt_Update
	delete: PagesDocAccessFields_updatedAt_Delete
}

type PagesDocAccessFields_updatedAt_Create {
	permission: Boolean!
}

type PagesDocAccessFields_updatedAt_Read {
	permission: Boolean!
}

type PagesDocAccessFields_updatedAt_Update {
	permission: Boolean!
}

type PagesDocAccessFields_updatedAt_Delete {
	permission: Boolean!
}

type PagesDocAccessFields_createdAt {
	create: PagesDocAccessFields_createdAt_Create
	read: PagesDocAccessFields_createdAt_Read
	update: PagesDocAccessFields_createdAt_Update
	delete: PagesDocAccessFields_createdAt_Delete
}

type PagesDocAccessFields_createdAt_Create {
	permission: Boolean!
}

type PagesDocAccessFields_createdAt_Read {
	permission: Boolean!
}

type PagesDocAccessFields_createdAt_Update {
	permission: Boolean!
}

type PagesDocAccessFields_createdAt_Delete {
	permission: Boolean!
}

type PagesCreateDocAccess {
	permission: Boolean!
	where: JSONObject
}

"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSONObject
	@specifiedBy(
		url: "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf"
	)

type PagesReadDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PagesUpdateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PagesDeleteDocAccess {
	permission: Boolean!
	where: JSONObject
}

type User {
	id: Int!
	roles: [User_roles!]
	username: String
	tenants: [User_Tenants!]
	updatedAt: DateTime
	createdAt: DateTime
	email: EmailAddress!
	resetPasswordToken: String
	resetPasswordExpiration: DateTime
	salt: String
	hash: String
	loginAttempts: Float
	lockUntil: DateTime
	sessions: [User_Sessions!]
}

enum User_roles {
	super_admin
	user
}

type User_Tenants {
	tenant: Tenant
	roles: [User_Tenants_roles!]
	id: String
}

enum User_Tenants_roles {
	tenant_admin
	tenant_viewer
}

"""
A field whose value conforms to the standard internet email address format as specified in HTML Spec: https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address.
"""
scalar EmailAddress
	@specifiedBy(
		url: "https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address"
	)

type User_Sessions {
	id: String
	createdAt: DateTime
	expiresAt: DateTime
}

type Users {
	docs: [User!]!
	hasNextPage: Boolean!
	hasPrevPage: Boolean!
	limit: Int!
	nextPage: Int
	offset: Int
	page: Int!
	pagingCounter: Int!
	prevPage: Int
	totalDocs: Int!
	totalPages: Int!
}

input User_where {
	roles: User_roles_operator
	username: User_username_operator
	tenants__tenant: User_tenants__tenant_operator
	tenants__roles: User_tenants__roles_operator
	tenants__id: User_tenants__id_operator
	updatedAt: User_updatedAt_operator
	createdAt: User_createdAt_operator
	email: User_email_operator
	sessions__id: User_sessions__id_operator
	sessions__createdAt: User_sessions__createdAt_operator
	sessions__expiresAt: User_sessions__expiresAt_operator
	id: User_id_operator
	AND: [User_where_and]
	OR: [User_where_or]
}

input User_roles_operator {
	equals: User_roles_Input
	not_equals: User_roles_Input
	in: [User_roles_Input]
	not_in: [User_roles_Input]
	all: [User_roles_Input]
	exists: Boolean
}

enum User_roles_Input {
	super_admin
	user
}

input User_username_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input User_tenants__tenant_operator {
	equals: JSON
	not_equals: JSON
	in: [JSON]
	not_in: [JSON]
	all: [JSON]
}

input User_tenants__roles_operator {
	equals: User_tenants__roles_Input
	not_equals: User_tenants__roles_Input
	in: [User_tenants__roles_Input]
	not_in: [User_tenants__roles_Input]
	all: [User_tenants__roles_Input]
}

enum User_tenants__roles_Input {
	tenant_admin
	tenant_viewer
}

input User_tenants__id_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input User_updatedAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input User_createdAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input User_email_operator {
	equals: EmailAddress
	not_equals: EmailAddress
	like: EmailAddress
	contains: EmailAddress
	in: [EmailAddress]
	not_in: [EmailAddress]
	all: [EmailAddress]
}

input User_sessions__id_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
}

input User_sessions__createdAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input User_sessions__expiresAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
}

input User_id_operator {
	equals: Int
	not_equals: Int
	greater_than_equal: Int
	greater_than: Int
	less_than_equal: Int
	less_than: Int
	exists: Boolean
}

input User_where_and {
	roles: User_roles_operator
	username: User_username_operator
	tenants__tenant: User_tenants__tenant_operator
	tenants__roles: User_tenants__roles_operator
	tenants__id: User_tenants__id_operator
	updatedAt: User_updatedAt_operator
	createdAt: User_createdAt_operator
	email: User_email_operator
	sessions__id: User_sessions__id_operator
	sessions__createdAt: User_sessions__createdAt_operator
	sessions__expiresAt: User_sessions__expiresAt_operator
	id: User_id_operator
	AND: [User_where_and]
	OR: [User_where_or]
}

input User_where_or {
	roles: User_roles_operator
	username: User_username_operator
	tenants__tenant: User_tenants__tenant_operator
	tenants__roles: User_tenants__roles_operator
	tenants__id: User_tenants__id_operator
	updatedAt: User_updatedAt_operator
	createdAt: User_createdAt_operator
	email: User_email_operator
	sessions__id: User_sessions__id_operator
	sessions__createdAt: User_sessions__createdAt_operator
	sessions__expiresAt: User_sessions__expiresAt_operator
	id: User_id_operator
	AND: [User_where_and]
	OR: [User_where_or]
}

type countUsers {
	totalDocs: Int
}

type usersDocAccess {
	fields: UsersDocAccessFields
	create: UsersCreateDocAccess
	read: UsersReadDocAccess
	update: UsersUpdateDocAccess
	delete: UsersDeleteDocAccess
	unlock: UsersUnlockDocAccess
}

type UsersDocAccessFields {
	roles: UsersDocAccessFields_roles
	username: UsersDocAccessFields_username
	tenants: UsersDocAccessFields_tenants
	updatedAt: UsersDocAccessFields_updatedAt
	createdAt: UsersDocAccessFields_createdAt
	email: UsersDocAccessFields_email
	sessions: UsersDocAccessFields_sessions
}

type UsersDocAccessFields_roles {
	create: UsersDocAccessFields_roles_Create
	read: UsersDocAccessFields_roles_Read
	update: UsersDocAccessFields_roles_Update
	delete: UsersDocAccessFields_roles_Delete
}

type UsersDocAccessFields_roles_Create {
	permission: Boolean!
}

type UsersDocAccessFields_roles_Read {
	permission: Boolean!
}

type UsersDocAccessFields_roles_Update {
	permission: Boolean!
}

type UsersDocAccessFields_roles_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_username {
	create: UsersDocAccessFields_username_Create
	read: UsersDocAccessFields_username_Read
	update: UsersDocAccessFields_username_Update
	delete: UsersDocAccessFields_username_Delete
}

type UsersDocAccessFields_username_Create {
	permission: Boolean!
}

type UsersDocAccessFields_username_Read {
	permission: Boolean!
}

type UsersDocAccessFields_username_Update {
	permission: Boolean!
}

type UsersDocAccessFields_username_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_tenants {
	create: UsersDocAccessFields_tenants_Create
	read: UsersDocAccessFields_tenants_Read
	update: UsersDocAccessFields_tenants_Update
	delete: UsersDocAccessFields_tenants_Delete
	fields: UsersDocAccessFields_tenants_Fields
}

type UsersDocAccessFields_tenants_Create {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_Read {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_Update {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_Fields {
	tenant: UsersDocAccessFields_tenants_tenant
	roles: UsersDocAccessFields_tenants_roles
	id: UsersDocAccessFields_tenants_id
}

type UsersDocAccessFields_tenants_tenant {
	create: UsersDocAccessFields_tenants_tenant_Create
	read: UsersDocAccessFields_tenants_tenant_Read
	update: UsersDocAccessFields_tenants_tenant_Update
	delete: UsersDocAccessFields_tenants_tenant_Delete
}

type UsersDocAccessFields_tenants_tenant_Create {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_tenant_Read {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_tenant_Update {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_tenant_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_roles {
	create: UsersDocAccessFields_tenants_roles_Create
	read: UsersDocAccessFields_tenants_roles_Read
	update: UsersDocAccessFields_tenants_roles_Update
	delete: UsersDocAccessFields_tenants_roles_Delete
}

type UsersDocAccessFields_tenants_roles_Create {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_roles_Read {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_roles_Update {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_roles_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_id {
	create: UsersDocAccessFields_tenants_id_Create
	read: UsersDocAccessFields_tenants_id_Read
	update: UsersDocAccessFields_tenants_id_Update
	delete: UsersDocAccessFields_tenants_id_Delete
}

type UsersDocAccessFields_tenants_id_Create {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_id_Read {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_id_Update {
	permission: Boolean!
}

type UsersDocAccessFields_tenants_id_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_updatedAt {
	create: UsersDocAccessFields_updatedAt_Create
	read: UsersDocAccessFields_updatedAt_Read
	update: UsersDocAccessFields_updatedAt_Update
	delete: UsersDocAccessFields_updatedAt_Delete
}

type UsersDocAccessFields_updatedAt_Create {
	permission: Boolean!
}

type UsersDocAccessFields_updatedAt_Read {
	permission: Boolean!
}

type UsersDocAccessFields_updatedAt_Update {
	permission: Boolean!
}

type UsersDocAccessFields_updatedAt_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_createdAt {
	create: UsersDocAccessFields_createdAt_Create
	read: UsersDocAccessFields_createdAt_Read
	update: UsersDocAccessFields_createdAt_Update
	delete: UsersDocAccessFields_createdAt_Delete
}

type UsersDocAccessFields_createdAt_Create {
	permission: Boolean!
}

type UsersDocAccessFields_createdAt_Read {
	permission: Boolean!
}

type UsersDocAccessFields_createdAt_Update {
	permission: Boolean!
}

type UsersDocAccessFields_createdAt_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_email {
	create: UsersDocAccessFields_email_Create
	read: UsersDocAccessFields_email_Read
	update: UsersDocAccessFields_email_Update
	delete: UsersDocAccessFields_email_Delete
}

type UsersDocAccessFields_email_Create {
	permission: Boolean!
}

type UsersDocAccessFields_email_Read {
	permission: Boolean!
}

type UsersDocAccessFields_email_Update {
	permission: Boolean!
}

type UsersDocAccessFields_email_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_sessions {
	create: UsersDocAccessFields_sessions_Create
	read: UsersDocAccessFields_sessions_Read
	update: UsersDocAccessFields_sessions_Update
	delete: UsersDocAccessFields_sessions_Delete
	fields: UsersDocAccessFields_sessions_Fields
}

type UsersDocAccessFields_sessions_Create {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_Read {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_Update {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_Fields {
	id: UsersDocAccessFields_sessions_id
	createdAt: UsersDocAccessFields_sessions_createdAt
	expiresAt: UsersDocAccessFields_sessions_expiresAt
}

type UsersDocAccessFields_sessions_id {
	create: UsersDocAccessFields_sessions_id_Create
	read: UsersDocAccessFields_sessions_id_Read
	update: UsersDocAccessFields_sessions_id_Update
	delete: UsersDocAccessFields_sessions_id_Delete
}

type UsersDocAccessFields_sessions_id_Create {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_id_Read {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_id_Update {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_id_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_createdAt {
	create: UsersDocAccessFields_sessions_createdAt_Create
	read: UsersDocAccessFields_sessions_createdAt_Read
	update: UsersDocAccessFields_sessions_createdAt_Update
	delete: UsersDocAccessFields_sessions_createdAt_Delete
}

type UsersDocAccessFields_sessions_createdAt_Create {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_createdAt_Read {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_createdAt_Update {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_createdAt_Delete {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_expiresAt {
	create: UsersDocAccessFields_sessions_expiresAt_Create
	read: UsersDocAccessFields_sessions_expiresAt_Read
	update: UsersDocAccessFields_sessions_expiresAt_Update
	delete: UsersDocAccessFields_sessions_expiresAt_Delete
}

type UsersDocAccessFields_sessions_expiresAt_Create {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_expiresAt_Read {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_expiresAt_Update {
	permission: Boolean!
}

type UsersDocAccessFields_sessions_expiresAt_Delete {
	permission: Boolean!
}

type UsersCreateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersReadDocAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersUpdateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersDeleteDocAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersUnlockDocAccess {
	permission: Boolean!
	where: JSONObject
}

type usersMe {
	collection: String
	exp: Int
	strategy: String
	token: String
	user: User
}

type Tenants {
	docs: [Tenant!]!
	hasNextPage: Boolean!
	hasPrevPage: Boolean!
	limit: Int!
	nextPage: Int
	offset: Int
	page: Int!
	pagingCounter: Int!
	prevPage: Int
	totalDocs: Int!
	totalPages: Int!
}

input Tenant_where {
	name: Tenant_name_operator
	domain: Tenant_domain_operator
	slug: Tenant_slug_operator
	allowPublicRead: Tenant_allowPublicRead_operator
	updatedAt: Tenant_updatedAt_operator
	createdAt: Tenant_createdAt_operator
	id: Tenant_id_operator
	AND: [Tenant_where_and]
	OR: [Tenant_where_or]
}

input Tenant_name_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
}

input Tenant_domain_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input Tenant_slug_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
}

input Tenant_allowPublicRead_operator {
	equals: Boolean
	not_equals: Boolean
	exists: Boolean
}

input Tenant_updatedAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input Tenant_createdAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input Tenant_id_operator {
	equals: Int
	not_equals: Int
	greater_than_equal: Int
	greater_than: Int
	less_than_equal: Int
	less_than: Int
	exists: Boolean
}

input Tenant_where_and {
	name: Tenant_name_operator
	domain: Tenant_domain_operator
	slug: Tenant_slug_operator
	allowPublicRead: Tenant_allowPublicRead_operator
	updatedAt: Tenant_updatedAt_operator
	createdAt: Tenant_createdAt_operator
	id: Tenant_id_operator
	AND: [Tenant_where_and]
	OR: [Tenant_where_or]
}

input Tenant_where_or {
	name: Tenant_name_operator
	domain: Tenant_domain_operator
	slug: Tenant_slug_operator
	allowPublicRead: Tenant_allowPublicRead_operator
	updatedAt: Tenant_updatedAt_operator
	createdAt: Tenant_createdAt_operator
	id: Tenant_id_operator
	AND: [Tenant_where_and]
	OR: [Tenant_where_or]
}

type countTenants {
	totalDocs: Int
}

type tenantsDocAccess {
	fields: TenantsDocAccessFields
	create: TenantsCreateDocAccess
	read: TenantsReadDocAccess
	update: TenantsUpdateDocAccess
	delete: TenantsDeleteDocAccess
}

type TenantsDocAccessFields {
	name: TenantsDocAccessFields_name
	domain: TenantsDocAccessFields_domain
	slug: TenantsDocAccessFields_slug
	allowPublicRead: TenantsDocAccessFields_allowPublicRead
	updatedAt: TenantsDocAccessFields_updatedAt
	createdAt: TenantsDocAccessFields_createdAt
}

type TenantsDocAccessFields_name {
	create: TenantsDocAccessFields_name_Create
	read: TenantsDocAccessFields_name_Read
	update: TenantsDocAccessFields_name_Update
	delete: TenantsDocAccessFields_name_Delete
}

type TenantsDocAccessFields_name_Create {
	permission: Boolean!
}

type TenantsDocAccessFields_name_Read {
	permission: Boolean!
}

type TenantsDocAccessFields_name_Update {
	permission: Boolean!
}

type TenantsDocAccessFields_name_Delete {
	permission: Boolean!
}

type TenantsDocAccessFields_domain {
	create: TenantsDocAccessFields_domain_Create
	read: TenantsDocAccessFields_domain_Read
	update: TenantsDocAccessFields_domain_Update
	delete: TenantsDocAccessFields_domain_Delete
}

type TenantsDocAccessFields_domain_Create {
	permission: Boolean!
}

type TenantsDocAccessFields_domain_Read {
	permission: Boolean!
}

type TenantsDocAccessFields_domain_Update {
	permission: Boolean!
}

type TenantsDocAccessFields_domain_Delete {
	permission: Boolean!
}

type TenantsDocAccessFields_slug {
	create: TenantsDocAccessFields_slug_Create
	read: TenantsDocAccessFields_slug_Read
	update: TenantsDocAccessFields_slug_Update
	delete: TenantsDocAccessFields_slug_Delete
}

type TenantsDocAccessFields_slug_Create {
	permission: Boolean!
}

type TenantsDocAccessFields_slug_Read {
	permission: Boolean!
}

type TenantsDocAccessFields_slug_Update {
	permission: Boolean!
}

type TenantsDocAccessFields_slug_Delete {
	permission: Boolean!
}

type TenantsDocAccessFields_allowPublicRead {
	create: TenantsDocAccessFields_allowPublicRead_Create
	read: TenantsDocAccessFields_allowPublicRead_Read
	update: TenantsDocAccessFields_allowPublicRead_Update
	delete: TenantsDocAccessFields_allowPublicRead_Delete
}

type TenantsDocAccessFields_allowPublicRead_Create {
	permission: Boolean!
}

type TenantsDocAccessFields_allowPublicRead_Read {
	permission: Boolean!
}

type TenantsDocAccessFields_allowPublicRead_Update {
	permission: Boolean!
}

type TenantsDocAccessFields_allowPublicRead_Delete {
	permission: Boolean!
}

type TenantsDocAccessFields_updatedAt {
	create: TenantsDocAccessFields_updatedAt_Create
	read: TenantsDocAccessFields_updatedAt_Read
	update: TenantsDocAccessFields_updatedAt_Update
	delete: TenantsDocAccessFields_updatedAt_Delete
}

type TenantsDocAccessFields_updatedAt_Create {
	permission: Boolean!
}

type TenantsDocAccessFields_updatedAt_Read {
	permission: Boolean!
}

type TenantsDocAccessFields_updatedAt_Update {
	permission: Boolean!
}

type TenantsDocAccessFields_updatedAt_Delete {
	permission: Boolean!
}

type TenantsDocAccessFields_createdAt {
	create: TenantsDocAccessFields_createdAt_Create
	read: TenantsDocAccessFields_createdAt_Read
	update: TenantsDocAccessFields_createdAt_Update
	delete: TenantsDocAccessFields_createdAt_Delete
}

type TenantsDocAccessFields_createdAt_Create {
	permission: Boolean!
}

type TenantsDocAccessFields_createdAt_Read {
	permission: Boolean!
}

type TenantsDocAccessFields_createdAt_Update {
	permission: Boolean!
}

type TenantsDocAccessFields_createdAt_Delete {
	permission: Boolean!
}

type TenantsCreateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type TenantsReadDocAccess {
	permission: Boolean!
	where: JSONObject
}

type TenantsUpdateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type TenantsDeleteDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocument {
	id: Int!
	document: PayloadLockedDocument_Document_Relationship
	globalSlug: String
	user: PayloadLockedDocument_User_Relationship!
	updatedAt: DateTime
	createdAt: DateTime
}

type PayloadLockedDocument_Document_Relationship {
	relationTo: PayloadLockedDocument_Document_RelationTo
	value: PayloadLockedDocument_Document
}

enum PayloadLockedDocument_Document_RelationTo {
	pages
	users
	tenants
}

union PayloadLockedDocument_Document = Page | User | Tenant

type PayloadLockedDocument_User_Relationship {
	relationTo: PayloadLockedDocument_User_RelationTo
	value: PayloadLockedDocument_User
}

enum PayloadLockedDocument_User_RelationTo {
	users
}

union PayloadLockedDocument_User = User

type PayloadLockedDocuments {
	docs: [PayloadLockedDocument!]!
	hasNextPage: Boolean!
	hasPrevPage: Boolean!
	limit: Int!
	nextPage: Int
	offset: Int
	page: Int!
	pagingCounter: Int!
	prevPage: Int
	totalDocs: Int!
	totalPages: Int!
}

input PayloadLockedDocument_where {
	document: PayloadLockedDocument_document_Relation
	globalSlug: PayloadLockedDocument_globalSlug_operator
	user: PayloadLockedDocument_user_Relation
	updatedAt: PayloadLockedDocument_updatedAt_operator
	createdAt: PayloadLockedDocument_createdAt_operator
	id: PayloadLockedDocument_id_operator
	AND: [PayloadLockedDocument_where_and]
	OR: [PayloadLockedDocument_where_or]
}

input PayloadLockedDocument_document_Relation {
	relationTo: PayloadLockedDocument_document_Relation_RelationTo
	value: JSON
}

enum PayloadLockedDocument_document_Relation_RelationTo {
	pages
	users
	tenants
}

input PayloadLockedDocument_globalSlug_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input PayloadLockedDocument_user_Relation {
	relationTo: PayloadLockedDocument_user_Relation_RelationTo
	value: JSON
}

enum PayloadLockedDocument_user_Relation_RelationTo {
	users
}

input PayloadLockedDocument_updatedAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input PayloadLockedDocument_createdAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input PayloadLockedDocument_id_operator {
	equals: Int
	not_equals: Int
	greater_than_equal: Int
	greater_than: Int
	less_than_equal: Int
	less_than: Int
	exists: Boolean
}

input PayloadLockedDocument_where_and {
	document: PayloadLockedDocument_document_Relation
	globalSlug: PayloadLockedDocument_globalSlug_operator
	user: PayloadLockedDocument_user_Relation
	updatedAt: PayloadLockedDocument_updatedAt_operator
	createdAt: PayloadLockedDocument_createdAt_operator
	id: PayloadLockedDocument_id_operator
	AND: [PayloadLockedDocument_where_and]
	OR: [PayloadLockedDocument_where_or]
}

input PayloadLockedDocument_where_or {
	document: PayloadLockedDocument_document_Relation
	globalSlug: PayloadLockedDocument_globalSlug_operator
	user: PayloadLockedDocument_user_Relation
	updatedAt: PayloadLockedDocument_updatedAt_operator
	createdAt: PayloadLockedDocument_createdAt_operator
	id: PayloadLockedDocument_id_operator
	AND: [PayloadLockedDocument_where_and]
	OR: [PayloadLockedDocument_where_or]
}

type countPayloadLockedDocuments {
	totalDocs: Int
}

type payload_locked_documentsDocAccess {
	fields: PayloadLockedDocumentsDocAccessFields
	create: PayloadLockedDocumentsCreateDocAccess
	read: PayloadLockedDocumentsReadDocAccess
	update: PayloadLockedDocumentsUpdateDocAccess
	delete: PayloadLockedDocumentsDeleteDocAccess
}

type PayloadLockedDocumentsDocAccessFields {
	document: PayloadLockedDocumentsDocAccessFields_document
	globalSlug: PayloadLockedDocumentsDocAccessFields_globalSlug
	user: PayloadLockedDocumentsDocAccessFields_user
	updatedAt: PayloadLockedDocumentsDocAccessFields_updatedAt
	createdAt: PayloadLockedDocumentsDocAccessFields_createdAt
}

type PayloadLockedDocumentsDocAccessFields_document {
	create: PayloadLockedDocumentsDocAccessFields_document_Create
	read: PayloadLockedDocumentsDocAccessFields_document_Read
	update: PayloadLockedDocumentsDocAccessFields_document_Update
	delete: PayloadLockedDocumentsDocAccessFields_document_Delete
}

type PayloadLockedDocumentsDocAccessFields_document_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_document_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_document_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_document_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_globalSlug {
	create: PayloadLockedDocumentsDocAccessFields_globalSlug_Create
	read: PayloadLockedDocumentsDocAccessFields_globalSlug_Read
	update: PayloadLockedDocumentsDocAccessFields_globalSlug_Update
	delete: PayloadLockedDocumentsDocAccessFields_globalSlug_Delete
}

type PayloadLockedDocumentsDocAccessFields_globalSlug_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_globalSlug_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_globalSlug_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_globalSlug_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_user {
	create: PayloadLockedDocumentsDocAccessFields_user_Create
	read: PayloadLockedDocumentsDocAccessFields_user_Read
	update: PayloadLockedDocumentsDocAccessFields_user_Update
	delete: PayloadLockedDocumentsDocAccessFields_user_Delete
}

type PayloadLockedDocumentsDocAccessFields_user_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_user_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_user_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_user_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_updatedAt {
	create: PayloadLockedDocumentsDocAccessFields_updatedAt_Create
	read: PayloadLockedDocumentsDocAccessFields_updatedAt_Read
	update: PayloadLockedDocumentsDocAccessFields_updatedAt_Update
	delete: PayloadLockedDocumentsDocAccessFields_updatedAt_Delete
}

type PayloadLockedDocumentsDocAccessFields_updatedAt_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_updatedAt_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_updatedAt_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_updatedAt_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_createdAt {
	create: PayloadLockedDocumentsDocAccessFields_createdAt_Create
	read: PayloadLockedDocumentsDocAccessFields_createdAt_Read
	update: PayloadLockedDocumentsDocAccessFields_createdAt_Update
	delete: PayloadLockedDocumentsDocAccessFields_createdAt_Delete
}

type PayloadLockedDocumentsDocAccessFields_createdAt_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_createdAt_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_createdAt_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsDocAccessFields_createdAt_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsCreateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocumentsReadDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocumentsUpdateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocumentsDeleteDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreference {
	id: Int!
	user: PayloadPreference_User_Relationship!
	key: String
	value: JSON
	updatedAt: DateTime
	createdAt: DateTime
}

type PayloadPreference_User_Relationship {
	relationTo: PayloadPreference_User_RelationTo
	value: PayloadPreference_User
}

enum PayloadPreference_User_RelationTo {
	users
}

union PayloadPreference_User = User

type PayloadPreferences {
	docs: [PayloadPreference!]!
	hasNextPage: Boolean!
	hasPrevPage: Boolean!
	limit: Int!
	nextPage: Int
	offset: Int
	page: Int!
	pagingCounter: Int!
	prevPage: Int
	totalDocs: Int!
	totalPages: Int!
}

input PayloadPreference_where {
	user: PayloadPreference_user_Relation
	key: PayloadPreference_key_operator
	value: PayloadPreference_value_operator
	updatedAt: PayloadPreference_updatedAt_operator
	createdAt: PayloadPreference_createdAt_operator
	id: PayloadPreference_id_operator
	AND: [PayloadPreference_where_and]
	OR: [PayloadPreference_where_or]
}

input PayloadPreference_user_Relation {
	relationTo: PayloadPreference_user_Relation_RelationTo
	value: JSON
}

enum PayloadPreference_user_Relation_RelationTo {
	users
}

input PayloadPreference_key_operator {
	equals: String
	not_equals: String
	like: String
	contains: String
	in: [String]
	not_in: [String]
	all: [String]
	exists: Boolean
}

input PayloadPreference_value_operator {
	equals: JSON
	not_equals: JSON
	like: JSON
	contains: JSON
	within: JSON
	intersects: JSON
	exists: Boolean
}

input PayloadPreference_updatedAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input PayloadPreference_createdAt_operator {
	equals: DateTime
	not_equals: DateTime
	greater_than_equal: DateTime
	greater_than: DateTime
	less_than_equal: DateTime
	less_than: DateTime
	like: DateTime
	exists: Boolean
}

input PayloadPreference_id_operator {
	equals: Int
	not_equals: Int
	greater_than_equal: Int
	greater_than: Int
	less_than_equal: Int
	less_than: Int
	exists: Boolean
}

input PayloadPreference_where_and {
	user: PayloadPreference_user_Relation
	key: PayloadPreference_key_operator
	value: PayloadPreference_value_operator
	updatedAt: PayloadPreference_updatedAt_operator
	createdAt: PayloadPreference_createdAt_operator
	id: PayloadPreference_id_operator
	AND: [PayloadPreference_where_and]
	OR: [PayloadPreference_where_or]
}

input PayloadPreference_where_or {
	user: PayloadPreference_user_Relation
	key: PayloadPreference_key_operator
	value: PayloadPreference_value_operator
	updatedAt: PayloadPreference_updatedAt_operator
	createdAt: PayloadPreference_createdAt_operator
	id: PayloadPreference_id_operator
	AND: [PayloadPreference_where_and]
	OR: [PayloadPreference_where_or]
}

type countPayloadPreferences {
	totalDocs: Int
}

type payload_preferencesDocAccess {
	fields: PayloadPreferencesDocAccessFields
	create: PayloadPreferencesCreateDocAccess
	read: PayloadPreferencesReadDocAccess
	update: PayloadPreferencesUpdateDocAccess
	delete: PayloadPreferencesDeleteDocAccess
}

type PayloadPreferencesDocAccessFields {
	user: PayloadPreferencesDocAccessFields_user
	key: PayloadPreferencesDocAccessFields_key
	value: PayloadPreferencesDocAccessFields_value
	updatedAt: PayloadPreferencesDocAccessFields_updatedAt
	createdAt: PayloadPreferencesDocAccessFields_createdAt
}

type PayloadPreferencesDocAccessFields_user {
	create: PayloadPreferencesDocAccessFields_user_Create
	read: PayloadPreferencesDocAccessFields_user_Read
	update: PayloadPreferencesDocAccessFields_user_Update
	delete: PayloadPreferencesDocAccessFields_user_Delete
}

type PayloadPreferencesDocAccessFields_user_Create {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_user_Read {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_user_Update {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_user_Delete {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_key {
	create: PayloadPreferencesDocAccessFields_key_Create
	read: PayloadPreferencesDocAccessFields_key_Read
	update: PayloadPreferencesDocAccessFields_key_Update
	delete: PayloadPreferencesDocAccessFields_key_Delete
}

type PayloadPreferencesDocAccessFields_key_Create {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_key_Read {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_key_Update {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_key_Delete {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_value {
	create: PayloadPreferencesDocAccessFields_value_Create
	read: PayloadPreferencesDocAccessFields_value_Read
	update: PayloadPreferencesDocAccessFields_value_Update
	delete: PayloadPreferencesDocAccessFields_value_Delete
}

type PayloadPreferencesDocAccessFields_value_Create {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_value_Read {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_value_Update {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_value_Delete {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_updatedAt {
	create: PayloadPreferencesDocAccessFields_updatedAt_Create
	read: PayloadPreferencesDocAccessFields_updatedAt_Read
	update: PayloadPreferencesDocAccessFields_updatedAt_Update
	delete: PayloadPreferencesDocAccessFields_updatedAt_Delete
}

type PayloadPreferencesDocAccessFields_updatedAt_Create {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_updatedAt_Read {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_updatedAt_Update {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_updatedAt_Delete {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_createdAt {
	create: PayloadPreferencesDocAccessFields_createdAt_Create
	read: PayloadPreferencesDocAccessFields_createdAt_Read
	update: PayloadPreferencesDocAccessFields_createdAt_Update
	delete: PayloadPreferencesDocAccessFields_createdAt_Delete
}

type PayloadPreferencesDocAccessFields_createdAt_Create {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_createdAt_Read {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_createdAt_Update {
	permission: Boolean!
}

type PayloadPreferencesDocAccessFields_createdAt_Delete {
	permission: Boolean!
}

type PayloadPreferencesCreateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreferencesReadDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreferencesUpdateDocAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreferencesDeleteDocAccess {
	permission: Boolean!
	where: JSONObject
}

type Access {
	canAccessAdmin: Boolean!
	pages: pagesAccess
	users: usersAccess
	tenants: tenantsAccess
	payload_locked_documents: payload_locked_documentsAccess
	payload_preferences: payload_preferencesAccess
}

type pagesAccess {
	fields: PagesFields
	create: PagesCreateAccess
	read: PagesReadAccess
	update: PagesUpdateAccess
	delete: PagesDeleteAccess
}

type PagesFields {
	tenant: PagesFields_tenant
	title: PagesFields_title
	slug: PagesFields_slug
	updatedAt: PagesFields_updatedAt
	createdAt: PagesFields_createdAt
}

type PagesFields_tenant {
	create: PagesFields_tenant_Create
	read: PagesFields_tenant_Read
	update: PagesFields_tenant_Update
	delete: PagesFields_tenant_Delete
}

type PagesFields_tenant_Create {
	permission: Boolean!
}

type PagesFields_tenant_Read {
	permission: Boolean!
}

type PagesFields_tenant_Update {
	permission: Boolean!
}

type PagesFields_tenant_Delete {
	permission: Boolean!
}

type PagesFields_title {
	create: PagesFields_title_Create
	read: PagesFields_title_Read
	update: PagesFields_title_Update
	delete: PagesFields_title_Delete
}

type PagesFields_title_Create {
	permission: Boolean!
}

type PagesFields_title_Read {
	permission: Boolean!
}

type PagesFields_title_Update {
	permission: Boolean!
}

type PagesFields_title_Delete {
	permission: Boolean!
}

type PagesFields_slug {
	create: PagesFields_slug_Create
	read: PagesFields_slug_Read
	update: PagesFields_slug_Update
	delete: PagesFields_slug_Delete
}

type PagesFields_slug_Create {
	permission: Boolean!
}

type PagesFields_slug_Read {
	permission: Boolean!
}

type PagesFields_slug_Update {
	permission: Boolean!
}

type PagesFields_slug_Delete {
	permission: Boolean!
}

type PagesFields_updatedAt {
	create: PagesFields_updatedAt_Create
	read: PagesFields_updatedAt_Read
	update: PagesFields_updatedAt_Update
	delete: PagesFields_updatedAt_Delete
}

type PagesFields_updatedAt_Create {
	permission: Boolean!
}

type PagesFields_updatedAt_Read {
	permission: Boolean!
}

type PagesFields_updatedAt_Update {
	permission: Boolean!
}

type PagesFields_updatedAt_Delete {
	permission: Boolean!
}

type PagesFields_createdAt {
	create: PagesFields_createdAt_Create
	read: PagesFields_createdAt_Read
	update: PagesFields_createdAt_Update
	delete: PagesFields_createdAt_Delete
}

type PagesFields_createdAt_Create {
	permission: Boolean!
}

type PagesFields_createdAt_Read {
	permission: Boolean!
}

type PagesFields_createdAt_Update {
	permission: Boolean!
}

type PagesFields_createdAt_Delete {
	permission: Boolean!
}

type PagesCreateAccess {
	permission: Boolean!
	where: JSONObject
}

type PagesReadAccess {
	permission: Boolean!
	where: JSONObject
}

type PagesUpdateAccess {
	permission: Boolean!
	where: JSONObject
}

type PagesDeleteAccess {
	permission: Boolean!
	where: JSONObject
}

type usersAccess {
	fields: UsersFields
	create: UsersCreateAccess
	read: UsersReadAccess
	update: UsersUpdateAccess
	delete: UsersDeleteAccess
	unlock: UsersUnlockAccess
}

type UsersFields {
	roles: UsersFields_roles
	username: UsersFields_username
	tenants: UsersFields_tenants
	updatedAt: UsersFields_updatedAt
	createdAt: UsersFields_createdAt
	email: UsersFields_email
	sessions: UsersFields_sessions
}

type UsersFields_roles {
	create: UsersFields_roles_Create
	read: UsersFields_roles_Read
	update: UsersFields_roles_Update
	delete: UsersFields_roles_Delete
}

type UsersFields_roles_Create {
	permission: Boolean!
}

type UsersFields_roles_Read {
	permission: Boolean!
}

type UsersFields_roles_Update {
	permission: Boolean!
}

type UsersFields_roles_Delete {
	permission: Boolean!
}

type UsersFields_username {
	create: UsersFields_username_Create
	read: UsersFields_username_Read
	update: UsersFields_username_Update
	delete: UsersFields_username_Delete
}

type UsersFields_username_Create {
	permission: Boolean!
}

type UsersFields_username_Read {
	permission: Boolean!
}

type UsersFields_username_Update {
	permission: Boolean!
}

type UsersFields_username_Delete {
	permission: Boolean!
}

type UsersFields_tenants {
	create: UsersFields_tenants_Create
	read: UsersFields_tenants_Read
	update: UsersFields_tenants_Update
	delete: UsersFields_tenants_Delete
	fields: UsersFields_tenants_Fields
}

type UsersFields_tenants_Create {
	permission: Boolean!
}

type UsersFields_tenants_Read {
	permission: Boolean!
}

type UsersFields_tenants_Update {
	permission: Boolean!
}

type UsersFields_tenants_Delete {
	permission: Boolean!
}

type UsersFields_tenants_Fields {
	tenant: UsersFields_tenants_tenant
	roles: UsersFields_tenants_roles
	id: UsersFields_tenants_id
}

type UsersFields_tenants_tenant {
	create: UsersFields_tenants_tenant_Create
	read: UsersFields_tenants_tenant_Read
	update: UsersFields_tenants_tenant_Update
	delete: UsersFields_tenants_tenant_Delete
}

type UsersFields_tenants_tenant_Create {
	permission: Boolean!
}

type UsersFields_tenants_tenant_Read {
	permission: Boolean!
}

type UsersFields_tenants_tenant_Update {
	permission: Boolean!
}

type UsersFields_tenants_tenant_Delete {
	permission: Boolean!
}

type UsersFields_tenants_roles {
	create: UsersFields_tenants_roles_Create
	read: UsersFields_tenants_roles_Read
	update: UsersFields_tenants_roles_Update
	delete: UsersFields_tenants_roles_Delete
}

type UsersFields_tenants_roles_Create {
	permission: Boolean!
}

type UsersFields_tenants_roles_Read {
	permission: Boolean!
}

type UsersFields_tenants_roles_Update {
	permission: Boolean!
}

type UsersFields_tenants_roles_Delete {
	permission: Boolean!
}

type UsersFields_tenants_id {
	create: UsersFields_tenants_id_Create
	read: UsersFields_tenants_id_Read
	update: UsersFields_tenants_id_Update
	delete: UsersFields_tenants_id_Delete
}

type UsersFields_tenants_id_Create {
	permission: Boolean!
}

type UsersFields_tenants_id_Read {
	permission: Boolean!
}

type UsersFields_tenants_id_Update {
	permission: Boolean!
}

type UsersFields_tenants_id_Delete {
	permission: Boolean!
}

type UsersFields_updatedAt {
	create: UsersFields_updatedAt_Create
	read: UsersFields_updatedAt_Read
	update: UsersFields_updatedAt_Update
	delete: UsersFields_updatedAt_Delete
}

type UsersFields_updatedAt_Create {
	permission: Boolean!
}

type UsersFields_updatedAt_Read {
	permission: Boolean!
}

type UsersFields_updatedAt_Update {
	permission: Boolean!
}

type UsersFields_updatedAt_Delete {
	permission: Boolean!
}

type UsersFields_createdAt {
	create: UsersFields_createdAt_Create
	read: UsersFields_createdAt_Read
	update: UsersFields_createdAt_Update
	delete: UsersFields_createdAt_Delete
}

type UsersFields_createdAt_Create {
	permission: Boolean!
}

type UsersFields_createdAt_Read {
	permission: Boolean!
}

type UsersFields_createdAt_Update {
	permission: Boolean!
}

type UsersFields_createdAt_Delete {
	permission: Boolean!
}

type UsersFields_email {
	create: UsersFields_email_Create
	read: UsersFields_email_Read
	update: UsersFields_email_Update
	delete: UsersFields_email_Delete
}

type UsersFields_email_Create {
	permission: Boolean!
}

type UsersFields_email_Read {
	permission: Boolean!
}

type UsersFields_email_Update {
	permission: Boolean!
}

type UsersFields_email_Delete {
	permission: Boolean!
}

type UsersFields_sessions {
	create: UsersFields_sessions_Create
	read: UsersFields_sessions_Read
	update: UsersFields_sessions_Update
	delete: UsersFields_sessions_Delete
	fields: UsersFields_sessions_Fields
}

type UsersFields_sessions_Create {
	permission: Boolean!
}

type UsersFields_sessions_Read {
	permission: Boolean!
}

type UsersFields_sessions_Update {
	permission: Boolean!
}

type UsersFields_sessions_Delete {
	permission: Boolean!
}

type UsersFields_sessions_Fields {
	id: UsersFields_sessions_id
	createdAt: UsersFields_sessions_createdAt
	expiresAt: UsersFields_sessions_expiresAt
}

type UsersFields_sessions_id {
	create: UsersFields_sessions_id_Create
	read: UsersFields_sessions_id_Read
	update: UsersFields_sessions_id_Update
	delete: UsersFields_sessions_id_Delete
}

type UsersFields_sessions_id_Create {
	permission: Boolean!
}

type UsersFields_sessions_id_Read {
	permission: Boolean!
}

type UsersFields_sessions_id_Update {
	permission: Boolean!
}

type UsersFields_sessions_id_Delete {
	permission: Boolean!
}

type UsersFields_sessions_createdAt {
	create: UsersFields_sessions_createdAt_Create
	read: UsersFields_sessions_createdAt_Read
	update: UsersFields_sessions_createdAt_Update
	delete: UsersFields_sessions_createdAt_Delete
}

type UsersFields_sessions_createdAt_Create {
	permission: Boolean!
}

type UsersFields_sessions_createdAt_Read {
	permission: Boolean!
}

type UsersFields_sessions_createdAt_Update {
	permission: Boolean!
}

type UsersFields_sessions_createdAt_Delete {
	permission: Boolean!
}

type UsersFields_sessions_expiresAt {
	create: UsersFields_sessions_expiresAt_Create
	read: UsersFields_sessions_expiresAt_Read
	update: UsersFields_sessions_expiresAt_Update
	delete: UsersFields_sessions_expiresAt_Delete
}

type UsersFields_sessions_expiresAt_Create {
	permission: Boolean!
}

type UsersFields_sessions_expiresAt_Read {
	permission: Boolean!
}

type UsersFields_sessions_expiresAt_Update {
	permission: Boolean!
}

type UsersFields_sessions_expiresAt_Delete {
	permission: Boolean!
}

type UsersCreateAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersReadAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersUpdateAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersDeleteAccess {
	permission: Boolean!
	where: JSONObject
}

type UsersUnlockAccess {
	permission: Boolean!
	where: JSONObject
}

type tenantsAccess {
	fields: TenantsFields
	create: TenantsCreateAccess
	read: TenantsReadAccess
	update: TenantsUpdateAccess
	delete: TenantsDeleteAccess
}

type TenantsFields {
	name: TenantsFields_name
	domain: TenantsFields_domain
	slug: TenantsFields_slug
	allowPublicRead: TenantsFields_allowPublicRead
	updatedAt: TenantsFields_updatedAt
	createdAt: TenantsFields_createdAt
}

type TenantsFields_name {
	create: TenantsFields_name_Create
	read: TenantsFields_name_Read
	update: TenantsFields_name_Update
	delete: TenantsFields_name_Delete
}

type TenantsFields_name_Create {
	permission: Boolean!
}

type TenantsFields_name_Read {
	permission: Boolean!
}

type TenantsFields_name_Update {
	permission: Boolean!
}

type TenantsFields_name_Delete {
	permission: Boolean!
}

type TenantsFields_domain {
	create: TenantsFields_domain_Create
	read: TenantsFields_domain_Read
	update: TenantsFields_domain_Update
	delete: TenantsFields_domain_Delete
}

type TenantsFields_domain_Create {
	permission: Boolean!
}

type TenantsFields_domain_Read {
	permission: Boolean!
}

type TenantsFields_domain_Update {
	permission: Boolean!
}

type TenantsFields_domain_Delete {
	permission: Boolean!
}

type TenantsFields_slug {
	create: TenantsFields_slug_Create
	read: TenantsFields_slug_Read
	update: TenantsFields_slug_Update
	delete: TenantsFields_slug_Delete
}

type TenantsFields_slug_Create {
	permission: Boolean!
}

type TenantsFields_slug_Read {
	permission: Boolean!
}

type TenantsFields_slug_Update {
	permission: Boolean!
}

type TenantsFields_slug_Delete {
	permission: Boolean!
}

type TenantsFields_allowPublicRead {
	create: TenantsFields_allowPublicRead_Create
	read: TenantsFields_allowPublicRead_Read
	update: TenantsFields_allowPublicRead_Update
	delete: TenantsFields_allowPublicRead_Delete
}

type TenantsFields_allowPublicRead_Create {
	permission: Boolean!
}

type TenantsFields_allowPublicRead_Read {
	permission: Boolean!
}

type TenantsFields_allowPublicRead_Update {
	permission: Boolean!
}

type TenantsFields_allowPublicRead_Delete {
	permission: Boolean!
}

type TenantsFields_updatedAt {
	create: TenantsFields_updatedAt_Create
	read: TenantsFields_updatedAt_Read
	update: TenantsFields_updatedAt_Update
	delete: TenantsFields_updatedAt_Delete
}

type TenantsFields_updatedAt_Create {
	permission: Boolean!
}

type TenantsFields_updatedAt_Read {
	permission: Boolean!
}

type TenantsFields_updatedAt_Update {
	permission: Boolean!
}

type TenantsFields_updatedAt_Delete {
	permission: Boolean!
}

type TenantsFields_createdAt {
	create: TenantsFields_createdAt_Create
	read: TenantsFields_createdAt_Read
	update: TenantsFields_createdAt_Update
	delete: TenantsFields_createdAt_Delete
}

type TenantsFields_createdAt_Create {
	permission: Boolean!
}

type TenantsFields_createdAt_Read {
	permission: Boolean!
}

type TenantsFields_createdAt_Update {
	permission: Boolean!
}

type TenantsFields_createdAt_Delete {
	permission: Boolean!
}

type TenantsCreateAccess {
	permission: Boolean!
	where: JSONObject
}

type TenantsReadAccess {
	permission: Boolean!
	where: JSONObject
}

type TenantsUpdateAccess {
	permission: Boolean!
	where: JSONObject
}

type TenantsDeleteAccess {
	permission: Boolean!
	where: JSONObject
}

type payload_locked_documentsAccess {
	fields: PayloadLockedDocumentsFields
	create: PayloadLockedDocumentsCreateAccess
	read: PayloadLockedDocumentsReadAccess
	update: PayloadLockedDocumentsUpdateAccess
	delete: PayloadLockedDocumentsDeleteAccess
}

type PayloadLockedDocumentsFields {
	document: PayloadLockedDocumentsFields_document
	globalSlug: PayloadLockedDocumentsFields_globalSlug
	user: PayloadLockedDocumentsFields_user
	updatedAt: PayloadLockedDocumentsFields_updatedAt
	createdAt: PayloadLockedDocumentsFields_createdAt
}

type PayloadLockedDocumentsFields_document {
	create: PayloadLockedDocumentsFields_document_Create
	read: PayloadLockedDocumentsFields_document_Read
	update: PayloadLockedDocumentsFields_document_Update
	delete: PayloadLockedDocumentsFields_document_Delete
}

type PayloadLockedDocumentsFields_document_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_document_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_document_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_document_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_globalSlug {
	create: PayloadLockedDocumentsFields_globalSlug_Create
	read: PayloadLockedDocumentsFields_globalSlug_Read
	update: PayloadLockedDocumentsFields_globalSlug_Update
	delete: PayloadLockedDocumentsFields_globalSlug_Delete
}

type PayloadLockedDocumentsFields_globalSlug_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_globalSlug_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_globalSlug_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_globalSlug_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_user {
	create: PayloadLockedDocumentsFields_user_Create
	read: PayloadLockedDocumentsFields_user_Read
	update: PayloadLockedDocumentsFields_user_Update
	delete: PayloadLockedDocumentsFields_user_Delete
}

type PayloadLockedDocumentsFields_user_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_user_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_user_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_user_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_updatedAt {
	create: PayloadLockedDocumentsFields_updatedAt_Create
	read: PayloadLockedDocumentsFields_updatedAt_Read
	update: PayloadLockedDocumentsFields_updatedAt_Update
	delete: PayloadLockedDocumentsFields_updatedAt_Delete
}

type PayloadLockedDocumentsFields_updatedAt_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_updatedAt_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_updatedAt_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_updatedAt_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_createdAt {
	create: PayloadLockedDocumentsFields_createdAt_Create
	read: PayloadLockedDocumentsFields_createdAt_Read
	update: PayloadLockedDocumentsFields_createdAt_Update
	delete: PayloadLockedDocumentsFields_createdAt_Delete
}

type PayloadLockedDocumentsFields_createdAt_Create {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_createdAt_Read {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_createdAt_Update {
	permission: Boolean!
}

type PayloadLockedDocumentsFields_createdAt_Delete {
	permission: Boolean!
}

type PayloadLockedDocumentsCreateAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocumentsReadAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocumentsUpdateAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadLockedDocumentsDeleteAccess {
	permission: Boolean!
	where: JSONObject
}

type payload_preferencesAccess {
	fields: PayloadPreferencesFields
	create: PayloadPreferencesCreateAccess
	read: PayloadPreferencesReadAccess
	update: PayloadPreferencesUpdateAccess
	delete: PayloadPreferencesDeleteAccess
}

type PayloadPreferencesFields {
	user: PayloadPreferencesFields_user
	key: PayloadPreferencesFields_key
	value: PayloadPreferencesFields_value
	updatedAt: PayloadPreferencesFields_updatedAt
	createdAt: PayloadPreferencesFields_createdAt
}

type PayloadPreferencesFields_user {
	create: PayloadPreferencesFields_user_Create
	read: PayloadPreferencesFields_user_Read
	update: PayloadPreferencesFields_user_Update
	delete: PayloadPreferencesFields_user_Delete
}

type PayloadPreferencesFields_user_Create {
	permission: Boolean!
}

type PayloadPreferencesFields_user_Read {
	permission: Boolean!
}

type PayloadPreferencesFields_user_Update {
	permission: Boolean!
}

type PayloadPreferencesFields_user_Delete {
	permission: Boolean!
}

type PayloadPreferencesFields_key {
	create: PayloadPreferencesFields_key_Create
	read: PayloadPreferencesFields_key_Read
	update: PayloadPreferencesFields_key_Update
	delete: PayloadPreferencesFields_key_Delete
}

type PayloadPreferencesFields_key_Create {
	permission: Boolean!
}

type PayloadPreferencesFields_key_Read {
	permission: Boolean!
}

type PayloadPreferencesFields_key_Update {
	permission: Boolean!
}

type PayloadPreferencesFields_key_Delete {
	permission: Boolean!
}

type PayloadPreferencesFields_value {
	create: PayloadPreferencesFields_value_Create
	read: PayloadPreferencesFields_value_Read
	update: PayloadPreferencesFields_value_Update
	delete: PayloadPreferencesFields_value_Delete
}

type PayloadPreferencesFields_value_Create {
	permission: Boolean!
}

type PayloadPreferencesFields_value_Read {
	permission: Boolean!
}

type PayloadPreferencesFields_value_Update {
	permission: Boolean!
}

type PayloadPreferencesFields_value_Delete {
	permission: Boolean!
}

type PayloadPreferencesFields_updatedAt {
	create: PayloadPreferencesFields_updatedAt_Create
	read: PayloadPreferencesFields_updatedAt_Read
	update: PayloadPreferencesFields_updatedAt_Update
	delete: PayloadPreferencesFields_updatedAt_Delete
}

type PayloadPreferencesFields_updatedAt_Create {
	permission: Boolean!
}

type PayloadPreferencesFields_updatedAt_Read {
	permission: Boolean!
}

type PayloadPreferencesFields_updatedAt_Update {
	permission: Boolean!
}

type PayloadPreferencesFields_updatedAt_Delete {
	permission: Boolean!
}

type PayloadPreferencesFields_createdAt {
	create: PayloadPreferencesFields_createdAt_Create
	read: PayloadPreferencesFields_createdAt_Read
	update: PayloadPreferencesFields_createdAt_Update
	delete: PayloadPreferencesFields_createdAt_Delete
}

type PayloadPreferencesFields_createdAt_Create {
	permission: Boolean!
}

type PayloadPreferencesFields_createdAt_Read {
	permission: Boolean!
}

type PayloadPreferencesFields_createdAt_Update {
	permission: Boolean!
}

type PayloadPreferencesFields_createdAt_Delete {
	permission: Boolean!
}

type PayloadPreferencesCreateAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreferencesReadAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreferencesUpdateAccess {
	permission: Boolean!
	where: JSONObject
}

type PayloadPreferencesDeleteAccess {
	permission: Boolean!
	where: JSONObject
}

type Mutation {
	createPage(data: mutationPageInput!, draft: Boolean): Page
	updatePage(
		id: Int!
		autosave: Boolean
		data: mutationPageUpdateInput!
		draft: Boolean
		trash: Boolean
	): Page
	deletePage(id: Int!, trash: Boolean): Page
	duplicatePage(id: Int!, data: mutationPageInput!): Page
	createUser(data: mutationUserInput!, draft: Boolean): User
	updateUser(
		id: Int!
		autosave: Boolean
		data: mutationUserUpdateInput!
		draft: Boolean
		trash: Boolean
	): User
	deleteUser(id: Int!, trash: Boolean): User
	refreshTokenUser: usersRefreshedUser
	logoutUser(allSessions: Boolean): String
	unlockUser(email: String!): Boolean!
	loginUser(email: String!, password: String): usersLoginResult
	forgotPasswordUser(
		disableEmail: Boolean
		expiration: Int
		email: String!
	): Boolean!
	resetPasswordUser(password: String, token: String): usersResetPassword
	verifyEmailUser(token: String): Boolean
	createTenant(data: mutationTenantInput!, draft: Boolean): Tenant
	updateTenant(
		id: Int!
		autosave: Boolean
		data: mutationTenantUpdateInput!
		draft: Boolean
		trash: Boolean
	): Tenant
	deleteTenant(id: Int!, trash: Boolean): Tenant
	duplicateTenant(id: Int!, data: mutationTenantInput!): Tenant
	createPayloadLockedDocument(
		data: mutationPayloadLockedDocumentInput!
		draft: Boolean
	): PayloadLockedDocument
	updatePayloadLockedDocument(
		id: Int!
		autosave: Boolean
		data: mutationPayloadLockedDocumentUpdateInput!
		draft: Boolean
		trash: Boolean
	): PayloadLockedDocument
	deletePayloadLockedDocument(id: Int!, trash: Boolean): PayloadLockedDocument
	duplicatePayloadLockedDocument(
		id: Int!
		data: mutationPayloadLockedDocumentInput!
	): PayloadLockedDocument
	createPayloadPreference(
		data: mutationPayloadPreferenceInput!
		draft: Boolean
	): PayloadPreference
	updatePayloadPreference(
		id: Int!
		autosave: Boolean
		data: mutationPayloadPreferenceUpdateInput!
		draft: Boolean
		trash: Boolean
	): PayloadPreference
	deletePayloadPreference(id: Int!, trash: Boolean): PayloadPreference
	duplicatePayloadPreference(
		id: Int!
		data: mutationPayloadPreferenceInput!
	): PayloadPreference
}

input mutationPageInput {
	tenant: Int
	title: String
	slug: String
	updatedAt: String
	createdAt: String
}

input mutationPageUpdateInput {
	tenant: Int
	title: String
	slug: String
	updatedAt: String
	createdAt: String
}

input mutationUserInput {
	roles: [User_roles_MutationInput]
	username: String
	tenants: [mutationUser_TenantsInput]
	updatedAt: String
	createdAt: String
	email: String!
	resetPasswordToken: String
	resetPasswordExpiration: String
	salt: String
	hash: String
	loginAttempts: Float
	lockUntil: String
	sessions: [mutationUser_SessionsInput]
	password: String!
}

enum User_roles_MutationInput {
	super_admin
	user
}

input mutationUser_TenantsInput {
	tenant: Int
	roles: [User_Tenants_roles_MutationInput]!
	id: String
}

enum User_Tenants_roles_MutationInput {
	tenant_admin
	tenant_viewer
}

input mutationUser_SessionsInput {
	id: String!
	createdAt: String
	expiresAt: String!
}

input mutationUserUpdateInput {
	roles: [UserUpdate_roles_MutationInput]
	username: String
	tenants: [mutationUserUpdate_TenantsInput]
	updatedAt: String
	createdAt: String
	email: String
	resetPasswordToken: String
	resetPasswordExpiration: String
	salt: String
	hash: String
	loginAttempts: Float
	lockUntil: String
	sessions: [mutationUserUpdate_SessionsInput]
	password: String
}

enum UserUpdate_roles_MutationInput {
	super_admin
	user
}

input mutationUserUpdate_TenantsInput {
	tenant: Int
	roles: [UserUpdate_Tenants_roles_MutationInput]!
	id: String
}

enum UserUpdate_Tenants_roles_MutationInput {
	tenant_admin
	tenant_viewer
}

input mutationUserUpdate_SessionsInput {
	id: String!
	createdAt: String
	expiresAt: String!
}

type usersRefreshedUser {
	exp: Int
	refreshedToken: String
	strategy: String
	user: usersJWT
}

type usersJWT {
	tenants: [usersJWT_Tenants!]
	email: EmailAddress!
	collection: String!
}

type usersJWT_Tenants {
	tenant: Tenant
	roles: [usersJWT_Tenants_roles!]
	id: String
}

enum usersJWT_Tenants_roles {
	tenant_admin
	tenant_viewer
}

type usersLoginResult {
	exp: Int
	token: String
	user: User
}

type usersResetPassword {
	token: String
	user: User
}

input mutationTenantInput {
	name: String!
	domain: String
	slug: String!
	allowPublicRead: Boolean
	updatedAt: String
	createdAt: String
}

input mutationTenantUpdateInput {
	name: String
	domain: String
	slug: String
	allowPublicRead: Boolean
	updatedAt: String
	createdAt: String
}

input mutationPayloadLockedDocumentInput {
	document: PayloadLockedDocument_DocumentRelationshipInput
	globalSlug: String
	user: PayloadLockedDocument_UserRelationshipInput
	updatedAt: String
	createdAt: String
}

input PayloadLockedDocument_DocumentRelationshipInput {
	relationTo: PayloadLockedDocument_DocumentRelationshipInputRelationTo
	value: JSON
}

enum PayloadLockedDocument_DocumentRelationshipInputRelationTo {
	pages
	users
	tenants
}

input PayloadLockedDocument_UserRelationshipInput {
	relationTo: PayloadLockedDocument_UserRelationshipInputRelationTo
	value: JSON
}

enum PayloadLockedDocument_UserRelationshipInputRelationTo {
	users
}

input mutationPayloadLockedDocumentUpdateInput {
	document: PayloadLockedDocumentUpdate_DocumentRelationshipInput
	globalSlug: String
	user: PayloadLockedDocumentUpdate_UserRelationshipInput
	updatedAt: String
	createdAt: String
}

input PayloadLockedDocumentUpdate_DocumentRelationshipInput {
	relationTo: PayloadLockedDocumentUpdate_DocumentRelationshipInputRelationTo
	value: JSON
}

enum PayloadLockedDocumentUpdate_DocumentRelationshipInputRelationTo {
	pages
	users
	tenants
}

input PayloadLockedDocumentUpdate_UserRelationshipInput {
	relationTo: PayloadLockedDocumentUpdate_UserRelationshipInputRelationTo
	value: JSON
}

enum PayloadLockedDocumentUpdate_UserRelationshipInputRelationTo {
	users
}

input mutationPayloadPreferenceInput {
	user: PayloadPreference_UserRelationshipInput
	key: String
	value: JSON
	updatedAt: String
	createdAt: String
}

input PayloadPreference_UserRelationshipInput {
	relationTo: PayloadPreference_UserRelationshipInputRelationTo
	value: JSON
}

enum PayloadPreference_UserRelationshipInputRelationTo {
	users
}

input mutationPayloadPreferenceUpdateInput {
	user: PayloadPreferenceUpdate_UserRelationshipInput
	key: String
	value: JSON
	updatedAt: String
	createdAt: String
}

input PayloadPreferenceUpdate_UserRelationshipInput {
	relationTo: PayloadPreferenceUpdate_UserRelationshipInputRelationTo
	value: JSON
}

enum PayloadPreferenceUpdate_UserRelationshipInputRelationTo {
	users
}
