/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  varchar,
  timestamp,
  integer,
  numeric,
  boolean,
  jsonb,
  serial,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_roles = pgEnum("enum_users_roles", [
  "super-admin",
  "user",
]);
export const enum_users_tenants_roles = pgEnum("enum_users_tenants_roles", [
  "tenant-admin",
  "tenant-viewer",
]);
export const enum_events_status = pgEnum("enum_events_status", [
  "draft",
  "published",
]);
export const enum__events_v_version_status = pgEnum(
  "enum__events_v_version_status",
  ["draft", "published"],
);
export const enum_bookings_payment_method = pgEnum(
  "enum_bookings_payment_method",
  ["payNow", "payLater"],
);
export const enum__bookings_v_version_payment_method = pgEnum(
  "enum__bookings_v_version_payment_method",
  ["payNow", "payLater"],
);
export const enum_emails_email_type = pgEnum("enum_emails_email_type", [
  "bookingConfirmationEmail",
  "bookingCancelledEmail",
  "bookingUpdatedEmail",
]);
export const enum_emails_status = pgEnum("enum_emails_status", [
  "draft",
  "published",
]);
export const enum__emails_v_version_email_type = pgEnum(
  "enum__emails_v_version_email_type",
  ["bookingConfirmationEmail", "bookingCancelledEmail", "bookingUpdatedEmail"],
);
export const enum__emails_v_version_status = pgEnum(
  "enum__emails_v_version_status",
  ["draft", "published"],
);
export const enum_payload_jobs_log_task_slug = pgEnum(
  "enum_payload_jobs_log_task_slug",
  ["inline", "schedulePublish"],
);
export const enum_payload_jobs_log_state = pgEnum(
  "enum_payload_jobs_log_state",
  ["failed", "succeeded"],
);
export const enum_payload_jobs_task_slug = pgEnum(
  "enum_payload_jobs_task_slug",
  ["inline", "schedulePublish"],
);

export const pages = pgTable(
  "pages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    title: varchar("title"),
    slug: varchar("slug").default("home"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("pages_tenant_idx").on(columns.tenant),
    index("pages_slug_idx").on(columns.slug),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
  ],
);

export const users_roles = pgTable(
  "users_roles",
  {
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    value: enum_users_roles("value"),
    id: uuid("id").defaultRandom().primaryKey(),
  },
  (columns) => [
    index("users_roles_order_idx").on(columns.order),
    index("users_roles_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users.id],
      name: "users_roles_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const users_tenants_roles = pgTable(
  "users_tenants_roles",
  {
    order: integer("order").notNull(),
    parent: varchar("parent_id").notNull(),
    value: enum_users_tenants_roles("value"),
    id: uuid("id").defaultRandom().primaryKey(),
  },
  (columns) => [
    index("users_tenants_roles_order_idx").on(columns.order),
    index("users_tenants_roles_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users_tenants.id],
      name: "users_tenants_roles_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const users_tenants = pgTable(
  "users_tenants",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tenant: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("users_tenants_order_idx").on(columns._order),
    index("users_tenants_parent_id_idx").on(columns._parentID),
    index("users_tenants_tenant_idx").on(columns.tenant),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_tenants_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    username: varchar("username"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_username_idx").on(columns.username),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const tenants = pgTable(
  "tenants",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name").notNull(),
    domain: varchar("domain"),
    slug: varchar("slug").notNull(),
    allowPublicRead: boolean("allow_public_read").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("tenants_name_idx").on(columns.name),
    uniqueIndex("tenants_slug_idx").on(columns.slug),
    index("tenants_allow_public_read_idx").on(columns.allowPublicRead),
    index("tenants_updated_at_idx").on(columns.updatedAt),
    index("tenants_created_at_idx").on(columns.createdAt),
  ],
);

export const customers = pgTable(
  "customers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    fullName: varchar("full_name"),
    email: varchar("email"),
    phone: varchar("phone"),
    stripeCustomerId: varchar("stripe_customer_id"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("customers_tenant_idx").on(columns.tenant),
    index("customers_updated_at_idx").on(columns.updatedAt),
    index("customers_created_at_idx").on(columns.createdAt),
    index("customers_deleted_at_idx").on(columns.deletedAt),
  ],
);

export const connected_accounts = pgTable(
  "connected_accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    default: boolean("default").default(false),
    name: varchar("name"),
    stripeAccountId: varchar("stripe_account_id"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("connected_accounts_tenant_idx").on(columns.tenant),
    index("connected_accounts_updated_at_idx").on(columns.updatedAt),
    index("connected_accounts_created_at_idx").on(columns.createdAt),
  ],
);

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payments_tenant_idx").on(columns.tenant),
    index("payments_updated_at_idx").on(columns.updatedAt),
    index("payments_created_at_idx").on(columns.createdAt),
  ],
);

export const payments_settings = pgTable(
  "payments_settings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payments_settings_updated_at_idx").on(columns.updatedAt),
    index("payments_settings_created_at_idx").on(columns.createdAt),
  ],
);

export const logs = pgTable(
  "logs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    user: uuid("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("logs_user_idx").on(columns.user),
    index("logs_updated_at_idx").on(columns.updatedAt),
    index("logs_created_at_idx").on(columns.createdAt),
  ],
);

export const events_schedules_schedule = pgTable(
  "events_schedules_schedule",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    isActive: boolean("is_active").default(true),
    scheduleName: varchar("schedule_name"),
    dtstart: timestamp("dtstart", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    dtend: timestamp("dtend", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    isRecurring: boolean("is_recurring").default(true),
    rrulestring: varchar("rrulestring"),
  },
  (columns) => [
    index("events_schedules_schedule_order_idx").on(columns._order),
    index("events_schedules_schedule_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_schedules_schedule_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events_prices = pgTable(
  "events_prices",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    stripePriceId: varchar("stripe_price_id"),
    isActive: boolean("is_active").default(true),
    label: varchar("label"),
    description: varchar("description"),
    amount: numeric("amount").default("0"),
    quantityUnit: numeric("quantity_unit").default("1"),
    quantity: numeric("quantity").default("0"),
  },
  (columns) => [
    index("events_prices_order_idx").on(columns._order),
    index("events_prices_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_prices_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events = pgTable(
  "events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    isActive: boolean("is_active").default(true),
    stripeProductId: varchar("stripe_product_id"),
    title: varchar("title"),
    description: jsonb("description"),
    thumbnail: uuid("thumbnail_id").references(() => media.id, {
      onDelete: "set null",
    }),
    maxQuantity: numeric("max_quantity").default("4"),
    minQuantity: numeric("min_quantity").default("1"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _status: enum_events_status("_status").default("draft"),
  },
  (columns) => [
    index("events_tenant_idx").on(columns.tenant),
    index("events_thumbnail_idx").on(columns.thumbnail),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
    index("events_deleted_at_idx").on(columns.deletedAt),
    index("events__status_idx").on(columns._status),
  ],
);

export const events_rels = pgTable(
  "events_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: uuid("media_id"),
  },
  (columns) => [
    index("events_rels_order_idx").on(columns.order),
    index("events_rels_parent_idx").on(columns.parent),
    index("events_rels_path_idx").on(columns.path),
    index("events_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [events.id],
      name: "events_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "events_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v_version_schedules_schedule = pgTable(
  "_events_v_version_schedules_schedule",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    isActive: boolean("is_active").default(true),
    scheduleName: varchar("schedule_name"),
    dtstart: timestamp("dtstart", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    dtend: timestamp("dtend", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    isRecurring: boolean("is_recurring").default(true),
    rrulestring: varchar("rrulestring"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_events_v_version_schedules_schedule_order_idx").on(columns._order),
    index("_events_v_version_schedules_schedule_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_version_schedules_schedule_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v_version_prices = pgTable(
  "_events_v_version_prices",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: uuid("id").defaultRandom().primaryKey(),
    stripePriceId: varchar("stripe_price_id"),
    isActive: boolean("is_active").default(true),
    label: varchar("label"),
    description: varchar("description"),
    amount: numeric("amount").default("0"),
    quantityUnit: numeric("quantity_unit").default("1"),
    quantity: numeric("quantity").default("0"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_events_v_version_prices_order_idx").on(columns._order),
    index("_events_v_version_prices_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_version_prices_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v = pgTable(
  "_events_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => events.id, {
      onDelete: "set null",
    }),
    version_tenant: uuid("version_tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    version_isActive: boolean("version_is_active").default(true),
    version_stripeProductId: varchar("version_stripe_product_id"),
    version_title: varchar("version_title"),
    version_description: jsonb("version_description"),
    version_thumbnail: uuid("version_thumbnail_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_maxQuantity: numeric("version_max_quantity").default("4"),
    version_minQuantity: numeric("version_min_quantity").default("1"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__events_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_events_v_parent_idx").on(columns.parent),
    index("_events_v_version_version_tenant_idx").on(columns.version_tenant),
    index("_events_v_version_version_thumbnail_idx").on(
      columns.version_thumbnail,
    ),
    index("_events_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_events_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_events_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_events_v_version_version__status_idx").on(columns.version__status),
    index("_events_v_created_at_idx").on(columns.createdAt),
    index("_events_v_updated_at_idx").on(columns.updatedAt),
    index("_events_v_latest_idx").on(columns.latest),
    index("_events_v_autosave_idx").on(columns.autosave),
  ],
);

export const _events_v_rels = pgTable(
  "_events_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: uuid("media_id"),
  },
  (columns) => [
    index("_events_v_rels_order_idx").on(columns.order),
    index("_events_v_rels_parent_idx").on(columns.parent),
    index("_events_v_rels_path_idx").on(columns.path),
    index("_events_v_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "_events_v_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const bookings = pgTable(
  "bookings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    eventRelation: uuid("event_relation_id").references(() => events.id, {
      onDelete: "set null",
    }),
    selectedScheduleInstanceData: jsonb("selected_schedule_instance_data"),
    dtstart: timestamp("dtstart", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    dtend: timestamp("dtend", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    customerRelation: uuid("customer_relation_id").references(
      () => customers.id,
      {
        onDelete: "set null",
      },
    ),
    overrideMaxQuantity: boolean("override_max_quantity"),
    eventSnapshot: jsonb("event_snapshot").default(sql`'{}'::jsonb`),
    customerSnapshot: jsonb("customer_snapshot").default(sql`'{}'::jsonb`),
    pricingSnapshot: jsonb("pricing_snapshot").default(sql`'{}'::jsonb`),
    rrulestring: varchar("rrulestring"),
    stripeCheckoutSessionId: varchar("stripe_checkout_session_id"),
    paymentStatus: varchar("payment_status"),
    paymentMethod: enum_bookings_payment_method("payment_method"),
    bookingConfirmationEmail: uuid("booking_confirmation_email_id").references(
      () => emails.id,
      {
        onDelete: "set null",
      },
    ),
    bookingCancelledEmail: uuid("booking_cancelled_email_id").references(
      () => emails.id,
      {
        onDelete: "set null",
      },
    ),
    bookingUpdatedEmail: uuid("booking_updated_email_id").references(
      () => emails.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("bookings_tenant_idx").on(columns.tenant),
    index("bookings_event_relation_idx").on(columns.eventRelation),
    index("bookings_customer_relation_idx").on(columns.customerRelation),
    index("bookings_booking_confirmation_email_idx").on(
      columns.bookingConfirmationEmail,
    ),
    index("bookings_booking_cancelled_email_idx").on(
      columns.bookingCancelledEmail,
    ),
    index("bookings_booking_updated_email_idx").on(columns.bookingUpdatedEmail),
    index("bookings_updated_at_idx").on(columns.updatedAt),
    index("bookings_created_at_idx").on(columns.createdAt),
    index("bookings_deleted_at_idx").on(columns.deletedAt),
  ],
);

export const _bookings_v = pgTable(
  "_bookings_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => bookings.id, {
      onDelete: "set null",
    }),
    version_tenant: uuid("version_tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    version_eventRelation: uuid("version_event_relation_id").references(
      () => events.id,
      {
        onDelete: "set null",
      },
    ),
    version_selectedScheduleInstanceData: jsonb(
      "version_selected_schedule_instance_data",
    ),
    version_dtstart: timestamp("version_dtstart", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    version_dtend: timestamp("version_dtend", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    version_customerRelation: uuid("version_customer_relation_id").references(
      () => customers.id,
      {
        onDelete: "set null",
      },
    ),
    version_overrideMaxQuantity: boolean("version_override_max_quantity"),
    version_eventSnapshot: jsonb("version_event_snapshot").default(
      sql`'{}'::jsonb`,
    ),
    version_customerSnapshot: jsonb("version_customer_snapshot").default(
      sql`'{}'::jsonb`,
    ),
    version_pricingSnapshot: jsonb("version_pricing_snapshot").default(
      sql`'{}'::jsonb`,
    ),
    version_rrulestring: varchar("version_rrulestring"),
    version_stripeCheckoutSessionId: varchar(
      "version_stripe_checkout_session_id",
    ),
    version_paymentStatus: varchar("version_payment_status"),
    version_paymentMethod: enum__bookings_v_version_payment_method(
      "version_payment_method",
    ),
    version_bookingConfirmationEmail: uuid(
      "version_booking_confirmation_email_id",
    ).references(() => emails.id, {
      onDelete: "set null",
    }),
    version_bookingCancelledEmail: uuid(
      "version_booking_cancelled_email_id",
    ).references(() => emails.id, {
      onDelete: "set null",
    }),
    version_bookingUpdatedEmail: uuid(
      "version_booking_updated_email_id",
    ).references(() => emails.id, {
      onDelete: "set null",
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("_bookings_v_parent_idx").on(columns.parent),
    index("_bookings_v_version_version_tenant_idx").on(columns.version_tenant),
    index("_bookings_v_version_version_event_relation_idx").on(
      columns.version_eventRelation,
    ),
    index("_bookings_v_version_version_customer_relation_idx").on(
      columns.version_customerRelation,
    ),
    index("_bookings_v_version_version_booking_confirmation_email_idx").on(
      columns.version_bookingConfirmationEmail,
    ),
    index("_bookings_v_version_version_booking_cancelled_email_idx").on(
      columns.version_bookingCancelledEmail,
    ),
    index("_bookings_v_version_version_booking_updated_email_idx").on(
      columns.version_bookingUpdatedEmail,
    ),
    index("_bookings_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_bookings_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_bookings_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_bookings_v_created_at_idx").on(columns.createdAt),
    index("_bookings_v_updated_at_idx").on(columns.updatedAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    title: varchar("title"),
    alt: varchar("alt"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width"),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height"),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize"),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_mobile_url: varchar("sizes_mobile_url"),
    sizes_mobile_width: numeric("sizes_mobile_width"),
    sizes_mobile_height: numeric("sizes_mobile_height"),
    sizes_mobile_mimeType: varchar("sizes_mobile_mime_type"),
    sizes_mobile_filesize: numeric("sizes_mobile_filesize"),
    sizes_mobile_filename: varchar("sizes_mobile_filename"),
    sizes_desktop_url: varchar("sizes_desktop_url"),
    sizes_desktop_width: numeric("sizes_desktop_width"),
    sizes_desktop_height: numeric("sizes_desktop_height"),
    sizes_desktop_mimeType: varchar("sizes_desktop_mime_type"),
    sizes_desktop_filesize: numeric("sizes_desktop_filesize"),
    sizes_desktop_filename: varchar("sizes_desktop_filename"),
  },
  (columns) => [
    index("media_tenant_idx").on(columns.tenant),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    index("media_deleted_at_idx").on(columns.deletedAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_mobile_sizes_mobile_filename_idx").on(
      columns.sizes_mobile_filename,
    ),
    index("media_sizes_desktop_sizes_desktop_filename_idx").on(
      columns.sizes_desktop_filename,
    ),
  ],
);

export const campaigns = pgTable(
  "campaigns",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    campaignName: varchar("campaign_name").notNull(),
    description: varchar("description"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("campaigns_tenant_idx").on(columns.tenant),
    index("campaigns_updated_at_idx").on(columns.updatedAt),
    index("campaigns_created_at_idx").on(columns.createdAt),
    index("campaigns_deleted_at_idx").on(columns.deletedAt),
  ],
);

export const campaigns_rels = pgTable(
  "campaigns_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    customersID: uuid("customers_id"),
  },
  (columns) => [
    index("campaigns_rels_order_idx").on(columns.order),
    index("campaigns_rels_parent_idx").on(columns.parent),
    index("campaigns_rels_path_idx").on(columns.path),
    index("campaigns_rels_customers_id_idx").on(columns.customersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [campaigns.id],
      name: "campaigns_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["customersID"]],
      foreignColumns: [customers.id],
      name: "campaigns_rels_customers_fk",
    }).onDelete("cascade"),
  ],
);

export const _campaigns_v = pgTable(
  "_campaigns_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => campaigns.id, {
      onDelete: "set null",
    }),
    version_tenant: uuid("version_tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    version_campaignName: varchar("version_campaign_name").notNull(),
    version_description: varchar("version_description"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("_campaigns_v_parent_idx").on(columns.parent),
    index("_campaigns_v_version_version_tenant_idx").on(columns.version_tenant),
    index("_campaigns_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_campaigns_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_campaigns_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_campaigns_v_created_at_idx").on(columns.createdAt),
    index("_campaigns_v_updated_at_idx").on(columns.updatedAt),
  ],
);

export const _campaigns_v_rels = pgTable(
  "_campaigns_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    customersID: uuid("customers_id"),
  },
  (columns) => [
    index("_campaigns_v_rels_order_idx").on(columns.order),
    index("_campaigns_v_rels_parent_idx").on(columns.parent),
    index("_campaigns_v_rels_path_idx").on(columns.path),
    index("_campaigns_v_rels_customers_id_idx").on(columns.customersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_campaigns_v.id],
      name: "_campaigns_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["customersID"]],
      foreignColumns: [customers.id],
      name: "_campaigns_v_rels_customers_fk",
    }).onDelete("cascade"),
  ],
);

export const emails = pgTable(
  "emails",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenant: uuid("tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    subject: varchar("subject"),
    preview: varchar("preview"),
    emailContent: jsonb("email_content"),
    emailType: enum_emails_email_type("email_type"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _status: enum_emails_status("_status").default("draft"),
  },
  (columns) => [
    index("emails_tenant_idx").on(columns.tenant),
    index("emails_updated_at_idx").on(columns.updatedAt),
    index("emails_created_at_idx").on(columns.createdAt),
    index("emails_deleted_at_idx").on(columns.deletedAt),
    index("emails__status_idx").on(columns._status),
  ],
);

export const _emails_v = pgTable(
  "_emails_v",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    parent: uuid("parent_id").references(() => emails.id, {
      onDelete: "set null",
    }),
    version_tenant: uuid("version_tenant_id").references(() => tenants.id, {
      onDelete: "set null",
    }),
    version_subject: varchar("version_subject"),
    version_preview: varchar("version_preview"),
    version_emailContent: jsonb("version_email_content"),
    version_emailType: enum__emails_v_version_email_type("version_email_type"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_deletedAt: timestamp("version_deleted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__emails_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_emails_v_parent_idx").on(columns.parent),
    index("_emails_v_version_version_tenant_idx").on(columns.version_tenant),
    index("_emails_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_emails_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_emails_v_version_version_deleted_at_idx").on(
      columns.version_deletedAt,
    ),
    index("_emails_v_version_version__status_idx").on(columns.version__status),
    index("_emails_v_created_at_idx").on(columns.createdAt),
    index("_emails_v_updated_at_idx").on(columns.updatedAt),
    index("_emails_v_latest_idx").on(columns.latest),
    index("_emails_v_autosave_idx").on(columns.autosave),
  ],
);

export const payload_jobs_log = pgTable(
  "payload_jobs_log",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    executedAt: timestamp("executed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug("task_slug").notNull(),
    taskID: varchar("task_i_d").notNull(),
    input: jsonb("input"),
    output: jsonb("output"),
    state: enum_payload_jobs_log_state("state").notNull(),
    error: jsonb("error"),
  },
  (columns) => [
    index("payload_jobs_log_order_idx").on(columns._order),
    index("payload_jobs_log_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_jobs.id],
      name: "payload_jobs_log_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_jobs = pgTable(
  "payload_jobs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    input: jsonb("input"),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    totalTried: numeric("total_tried").default("0"),
    hasError: boolean("has_error").default(false),
    error: jsonb("error"),
    taskSlug: enum_payload_jobs_task_slug("task_slug"),
    queue: varchar("queue").default("default"),
    waitUntil: timestamp("wait_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    processing: boolean("processing").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_jobs_completed_at_idx").on(columns.completedAt),
    index("payload_jobs_total_tried_idx").on(columns.totalTried),
    index("payload_jobs_has_error_idx").on(columns.hasError),
    index("payload_jobs_task_slug_idx").on(columns.taskSlug),
    index("payload_jobs_queue_idx").on(columns.queue),
    index("payload_jobs_wait_until_idx").on(columns.waitUntil),
    index("payload_jobs_processing_idx").on(columns.processing),
    index("payload_jobs_updated_at_idx").on(columns.updatedAt),
    index("payload_jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: uuid("pages_id"),
    usersID: uuid("users_id"),
    tenantsID: uuid("tenants_id"),
    customersID: uuid("customers_id"),
    connectedAccountsID: uuid("connected_accounts_id"),
    paymentsID: uuid("payments_id"),
    paymentsSettingsID: uuid("payments_settings_id"),
    logsID: uuid("logs_id"),
    eventsID: uuid("events_id"),
    bookingsID: uuid("bookings_id"),
    mediaID: uuid("media_id"),
    campaignsID: uuid("campaigns_id"),
    emailsID: uuid("emails_id"),
    "payload-jobsID": uuid("payload_jobs_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_tenants_id_idx").on(columns.tenantsID),
    index("payload_locked_documents_rels_customers_id_idx").on(
      columns.customersID,
    ),
    index("payload_locked_documents_rels_connected_accounts_id_idx").on(
      columns.connectedAccountsID,
    ),
    index("payload_locked_documents_rels_payments_id_idx").on(
      columns.paymentsID,
    ),
    index("payload_locked_documents_rels_payments_settings_id_idx").on(
      columns.paymentsSettingsID,
    ),
    index("payload_locked_documents_rels_logs_id_idx").on(columns.logsID),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    index("payload_locked_documents_rels_bookings_id_idx").on(
      columns.bookingsID,
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_campaigns_id_idx").on(
      columns.campaignsID,
    ),
    index("payload_locked_documents_rels_emails_id_idx").on(columns.emailsID),
    index("payload_locked_documents_rels_payload_jobs_id_idx").on(
      columns["payload-jobsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tenantsID"]],
      foreignColumns: [tenants.id],
      name: "payload_locked_documents_rels_tenants_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["customersID"]],
      foreignColumns: [customers.id],
      name: "payload_locked_documents_rels_customers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["connectedAccountsID"]],
      foreignColumns: [connected_accounts.id],
      name: "payload_locked_documents_rels_connected_accounts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["paymentsID"]],
      foreignColumns: [payments.id],
      name: "payload_locked_documents_rels_payments_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["paymentsSettingsID"]],
      foreignColumns: [payments_settings.id],
      name: "payload_locked_documents_rels_payments_settings_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["logsID"]],
      foreignColumns: [logs.id],
      name: "payload_locked_documents_rels_logs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["bookingsID"]],
      foreignColumns: [bookings.id],
      name: "payload_locked_documents_rels_bookings_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["campaignsID"]],
      foreignColumns: [campaigns.id],
      name: "payload_locked_documents_rels_campaigns_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["emailsID"]],
      foreignColumns: [emails.id],
      name: "payload_locked_documents_rels_emails_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-jobsID"]],
      foreignColumns: [payload_jobs.id],
      name: "payload_locked_documents_rels_payload_jobs_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_pages = relations(pages, ({ one }) => ({
  tenant: one(tenants, {
    fields: [pages.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
}));
export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: "roles",
  }),
}));
export const relations_users_tenants_roles = relations(
  users_tenants_roles,
  ({ one }) => ({
    parent: one(users_tenants, {
      fields: [users_tenants_roles.parent],
      references: [users_tenants.id],
      relationName: "roles",
    }),
  }),
);
export const relations_users_tenants = relations(
  users_tenants,
  ({ one, many }) => ({
    _parentID: one(users, {
      fields: [users_tenants._parentID],
      references: [users.id],
      relationName: "tenants",
    }),
    tenant: one(tenants, {
      fields: [users_tenants.tenant],
      references: [tenants.id],
      relationName: "tenant",
    }),
    roles: many(users_tenants_roles, {
      relationName: "roles",
    }),
  }),
);
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: "roles",
  }),
  tenants: many(users_tenants, {
    relationName: "tenants",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_tenants = relations(tenants, () => ({}));
export const relations_customers = relations(customers, ({ one }) => ({
  tenant: one(tenants, {
    fields: [customers.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
}));
export const relations_connected_accounts = relations(
  connected_accounts,
  ({ one }) => ({
    tenant: one(tenants, {
      fields: [connected_accounts.tenant],
      references: [tenants.id],
      relationName: "tenant",
    }),
  }),
);
export const relations_payments = relations(payments, ({ one }) => ({
  tenant: one(tenants, {
    fields: [payments.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
}));
export const relations_payments_settings = relations(
  payments_settings,
  () => ({}),
);
export const relations_logs = relations(logs, ({ one }) => ({
  user: one(users, {
    fields: [logs.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_events_schedules_schedule = relations(
  events_schedules_schedule,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_schedules_schedule._parentID],
      references: [events.id],
      relationName: "schedules_schedule",
    }),
  }),
);
export const relations_events_prices = relations(events_prices, ({ one }) => ({
  _parentID: one(events, {
    fields: [events_prices._parentID],
    references: [events.id],
    relationName: "prices",
  }),
}));
export const relations_events_rels = relations(events_rels, ({ one }) => ({
  parent: one(events, {
    fields: [events_rels.parent],
    references: [events.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [events_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
}));
export const relations_events = relations(events, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [events.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
  thumbnail: one(media, {
    fields: [events.thumbnail],
    references: [media.id],
    relationName: "thumbnail",
  }),
  schedules_schedule: many(events_schedules_schedule, {
    relationName: "schedules_schedule",
  }),
  prices: many(events_prices, {
    relationName: "prices",
  }),
  _rels: many(events_rels, {
    relationName: "_rels",
  }),
}));
export const relations__events_v_version_schedules_schedule = relations(
  _events_v_version_schedules_schedule,
  ({ one }) => ({
    _parentID: one(_events_v, {
      fields: [_events_v_version_schedules_schedule._parentID],
      references: [_events_v.id],
      relationName: "version_schedules_schedule",
    }),
  }),
);
export const relations__events_v_version_prices = relations(
  _events_v_version_prices,
  ({ one }) => ({
    _parentID: one(_events_v, {
      fields: [_events_v_version_prices._parentID],
      references: [_events_v.id],
      relationName: "version_prices",
    }),
  }),
);
export const relations__events_v_rels = relations(
  _events_v_rels,
  ({ one }) => ({
    parent: one(_events_v, {
      fields: [_events_v_rels.parent],
      references: [_events_v.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [_events_v_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations__events_v = relations(_events_v, ({ one, many }) => ({
  parent: one(events, {
    fields: [_events_v.parent],
    references: [events.id],
    relationName: "parent",
  }),
  version_tenant: one(tenants, {
    fields: [_events_v.version_tenant],
    references: [tenants.id],
    relationName: "version_tenant",
  }),
  version_thumbnail: one(media, {
    fields: [_events_v.version_thumbnail],
    references: [media.id],
    relationName: "version_thumbnail",
  }),
  version_schedules_schedule: many(_events_v_version_schedules_schedule, {
    relationName: "version_schedules_schedule",
  }),
  version_prices: many(_events_v_version_prices, {
    relationName: "version_prices",
  }),
  _rels: many(_events_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_bookings = relations(bookings, ({ one }) => ({
  tenant: one(tenants, {
    fields: [bookings.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
  eventRelation: one(events, {
    fields: [bookings.eventRelation],
    references: [events.id],
    relationName: "eventRelation",
  }),
  customerRelation: one(customers, {
    fields: [bookings.customerRelation],
    references: [customers.id],
    relationName: "customerRelation",
  }),
  bookingConfirmationEmail: one(emails, {
    fields: [bookings.bookingConfirmationEmail],
    references: [emails.id],
    relationName: "bookingConfirmationEmail",
  }),
  bookingCancelledEmail: one(emails, {
    fields: [bookings.bookingCancelledEmail],
    references: [emails.id],
    relationName: "bookingCancelledEmail",
  }),
  bookingUpdatedEmail: one(emails, {
    fields: [bookings.bookingUpdatedEmail],
    references: [emails.id],
    relationName: "bookingUpdatedEmail",
  }),
}));
export const relations__bookings_v = relations(_bookings_v, ({ one }) => ({
  parent: one(bookings, {
    fields: [_bookings_v.parent],
    references: [bookings.id],
    relationName: "parent",
  }),
  version_tenant: one(tenants, {
    fields: [_bookings_v.version_tenant],
    references: [tenants.id],
    relationName: "version_tenant",
  }),
  version_eventRelation: one(events, {
    fields: [_bookings_v.version_eventRelation],
    references: [events.id],
    relationName: "version_eventRelation",
  }),
  version_customerRelation: one(customers, {
    fields: [_bookings_v.version_customerRelation],
    references: [customers.id],
    relationName: "version_customerRelation",
  }),
  version_bookingConfirmationEmail: one(emails, {
    fields: [_bookings_v.version_bookingConfirmationEmail],
    references: [emails.id],
    relationName: "version_bookingConfirmationEmail",
  }),
  version_bookingCancelledEmail: one(emails, {
    fields: [_bookings_v.version_bookingCancelledEmail],
    references: [emails.id],
    relationName: "version_bookingCancelledEmail",
  }),
  version_bookingUpdatedEmail: one(emails, {
    fields: [_bookings_v.version_bookingUpdatedEmail],
    references: [emails.id],
    relationName: "version_bookingUpdatedEmail",
  }),
}));
export const relations_media = relations(media, ({ one }) => ({
  tenant: one(tenants, {
    fields: [media.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
}));
export const relations_campaigns_rels = relations(
  campaigns_rels,
  ({ one }) => ({
    parent: one(campaigns, {
      fields: [campaigns_rels.parent],
      references: [campaigns.id],
      relationName: "_rels",
    }),
    customersID: one(customers, {
      fields: [campaigns_rels.customersID],
      references: [customers.id],
      relationName: "customers",
    }),
  }),
);
export const relations_campaigns = relations(campaigns, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [campaigns.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
  _rels: many(campaigns_rels, {
    relationName: "_rels",
  }),
}));
export const relations__campaigns_v_rels = relations(
  _campaigns_v_rels,
  ({ one }) => ({
    parent: one(_campaigns_v, {
      fields: [_campaigns_v_rels.parent],
      references: [_campaigns_v.id],
      relationName: "_rels",
    }),
    customersID: one(customers, {
      fields: [_campaigns_v_rels.customersID],
      references: [customers.id],
      relationName: "customers",
    }),
  }),
);
export const relations__campaigns_v = relations(
  _campaigns_v,
  ({ one, many }) => ({
    parent: one(campaigns, {
      fields: [_campaigns_v.parent],
      references: [campaigns.id],
      relationName: "parent",
    }),
    version_tenant: one(tenants, {
      fields: [_campaigns_v.version_tenant],
      references: [tenants.id],
      relationName: "version_tenant",
    }),
    _rels: many(_campaigns_v_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_emails = relations(emails, ({ one }) => ({
  tenant: one(tenants, {
    fields: [emails.tenant],
    references: [tenants.id],
    relationName: "tenant",
  }),
}));
export const relations__emails_v = relations(_emails_v, ({ one }) => ({
  parent: one(emails, {
    fields: [_emails_v.parent],
    references: [emails.id],
    relationName: "parent",
  }),
  version_tenant: one(tenants, {
    fields: [_emails_v.version_tenant],
    references: [tenants.id],
    relationName: "version_tenant",
  }),
}));
export const relations_payload_jobs_log = relations(
  payload_jobs_log,
  ({ one }) => ({
    _parentID: one(payload_jobs, {
      fields: [payload_jobs_log._parentID],
      references: [payload_jobs.id],
      relationName: "log",
    }),
  }),
);
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: "log",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    tenantsID: one(tenants, {
      fields: [payload_locked_documents_rels.tenantsID],
      references: [tenants.id],
      relationName: "tenants",
    }),
    customersID: one(customers, {
      fields: [payload_locked_documents_rels.customersID],
      references: [customers.id],
      relationName: "customers",
    }),
    connectedAccountsID: one(connected_accounts, {
      fields: [payload_locked_documents_rels.connectedAccountsID],
      references: [connected_accounts.id],
      relationName: "connectedAccounts",
    }),
    paymentsID: one(payments, {
      fields: [payload_locked_documents_rels.paymentsID],
      references: [payments.id],
      relationName: "payments",
    }),
    paymentsSettingsID: one(payments_settings, {
      fields: [payload_locked_documents_rels.paymentsSettingsID],
      references: [payments_settings.id],
      relationName: "paymentsSettings",
    }),
    logsID: one(logs, {
      fields: [payload_locked_documents_rels.logsID],
      references: [logs.id],
      relationName: "logs",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
    bookingsID: one(bookings, {
      fields: [payload_locked_documents_rels.bookingsID],
      references: [bookings.id],
      relationName: "bookings",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    campaignsID: one(campaigns, {
      fields: [payload_locked_documents_rels.campaignsID],
      references: [campaigns.id],
      relationName: "campaigns",
    }),
    emailsID: one(emails, {
      fields: [payload_locked_documents_rels.emailsID],
      references: [emails.id],
      relationName: "emails",
    }),
    "payload-jobsID": one(payload_jobs, {
      fields: [payload_locked_documents_rels["payload-jobsID"]],
      references: [payload_jobs.id],
      relationName: "payload-jobs",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_roles: typeof enum_users_roles;
  enum_users_tenants_roles: typeof enum_users_tenants_roles;
  enum_events_status: typeof enum_events_status;
  enum__events_v_version_status: typeof enum__events_v_version_status;
  enum_bookings_payment_method: typeof enum_bookings_payment_method;
  enum__bookings_v_version_payment_method: typeof enum__bookings_v_version_payment_method;
  enum_emails_email_type: typeof enum_emails_email_type;
  enum_emails_status: typeof enum_emails_status;
  enum__emails_v_version_email_type: typeof enum__emails_v_version_email_type;
  enum__emails_v_version_status: typeof enum__emails_v_version_status;
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug;
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state;
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug;
  pages: typeof pages;
  users_roles: typeof users_roles;
  users_tenants_roles: typeof users_tenants_roles;
  users_tenants: typeof users_tenants;
  users_sessions: typeof users_sessions;
  users: typeof users;
  tenants: typeof tenants;
  customers: typeof customers;
  connected_accounts: typeof connected_accounts;
  payments: typeof payments;
  payments_settings: typeof payments_settings;
  logs: typeof logs;
  events_schedules_schedule: typeof events_schedules_schedule;
  events_prices: typeof events_prices;
  events: typeof events;
  events_rels: typeof events_rels;
  _events_v_version_schedules_schedule: typeof _events_v_version_schedules_schedule;
  _events_v_version_prices: typeof _events_v_version_prices;
  _events_v: typeof _events_v;
  _events_v_rels: typeof _events_v_rels;
  bookings: typeof bookings;
  _bookings_v: typeof _bookings_v;
  media: typeof media;
  campaigns: typeof campaigns;
  campaigns_rels: typeof campaigns_rels;
  _campaigns_v: typeof _campaigns_v;
  _campaigns_v_rels: typeof _campaigns_v_rels;
  emails: typeof emails;
  _emails_v: typeof _emails_v;
  payload_jobs_log: typeof payload_jobs_log;
  payload_jobs: typeof payload_jobs;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_pages: typeof relations_pages;
  relations_users_roles: typeof relations_users_roles;
  relations_users_tenants_roles: typeof relations_users_tenants_roles;
  relations_users_tenants: typeof relations_users_tenants;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_tenants: typeof relations_tenants;
  relations_customers: typeof relations_customers;
  relations_connected_accounts: typeof relations_connected_accounts;
  relations_payments: typeof relations_payments;
  relations_payments_settings: typeof relations_payments_settings;
  relations_logs: typeof relations_logs;
  relations_events_schedules_schedule: typeof relations_events_schedules_schedule;
  relations_events_prices: typeof relations_events_prices;
  relations_events_rels: typeof relations_events_rels;
  relations_events: typeof relations_events;
  relations__events_v_version_schedules_schedule: typeof relations__events_v_version_schedules_schedule;
  relations__events_v_version_prices: typeof relations__events_v_version_prices;
  relations__events_v_rels: typeof relations__events_v_rels;
  relations__events_v: typeof relations__events_v;
  relations_bookings: typeof relations_bookings;
  relations__bookings_v: typeof relations__bookings_v;
  relations_media: typeof relations_media;
  relations_campaigns_rels: typeof relations_campaigns_rels;
  relations_campaigns: typeof relations_campaigns;
  relations__campaigns_v_rels: typeof relations__campaigns_v_rels;
  relations__campaigns_v: typeof relations__campaigns_v;
  relations_emails: typeof relations_emails;
  relations__emails_v: typeof relations__emails_v;
  relations_payload_jobs_log: typeof relations_payload_jobs_log;
  relations_payload_jobs: typeof relations_payload_jobs;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
